<template>
  <div>
    <blockquote class="blockquote text-center bg-white">
      <h1 class="mb-0">Chính sách</h1>
    </blockquote>
    <div class="container">
      <div class="bg-white p-2  rounded-3">
        <div class="row">
          <div class="col-md-12">
            <div class="accordion" id="accordionExample">
              <div class="accordion-item" v-for="(collapse, index) of collapses" :key="index">
                <h2 class="accordion-header" :id="`heading`+index">
                  <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                    :data-bs-target="`#collapseVip`+index" aria-expanded="false" :aria-controls="`collapseVip`+index">
                    {{ collapse.title }}
                  </button>
                </h2>
                <div :id="`collapseVip`+index" class="accordion-collapse collapse" :aria-labelledby="`heading`+index"
                  data-bs-parent="#accordionExample">
                  <div class="accordion-body" v-html="collapse.text">

                  </div>
                </div>
              </div>
              
            </div>


          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import load_api from '../../../../../api.json';

export default {
  metaInfo() {
    return {
      title: "Chính sách"
    }
  },
  data() {
    return {
      model: [],
      textdata:``,
      isOpen: 0,
      collapses: [
        {
          title: "Điều khoản dịch vụ e-Gate",
          text: `<h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;text-align:center;line-height:107%;font-size:21px;font-family:"Times New Roman",serif;color:#2F5496;'>Điều khoản dịch vụ ( Terms of Service )</h1>
          <h2 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:19px;font-family:"Times New Roman",serif;color:#2F5496;'>1.Điều khoản khi đăng k&iacute; t&agrave;i khoản:</h2>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>a</strong>.Để truy cập v&agrave; sử dụng dịch vụ,&nbsp;bạn phải đăng k&iacute; t&agrave;i khoản e-Gate(&ldquo; Account&rdquo;).&nbsp;Để &nbsp; &nbsp; &nbsp;ho&agrave;n tất việc đăng k&iacute; n&agrave;y,&nbsp;bạn phải cung cấp cho ch&uacute;ng t&ocirc;i họ t&ecirc;n đầy đủ theo ph&aacute;p l&yacute;,&nbsp;địa chỉ,&nbsp;số điện thoại,&nbsp;địa chỉ email hợp lệ v&agrave; bất k&igrave; th&ocirc;ng tin n&agrave;o kh&aacute;c được chỉ định theo y&ecirc;u cầu.&nbsp;e-Gate c&oacute; thể từ chối đơn đăng k&iacute; t&agrave;i khoản của bạn hoặc hủy t&agrave;i khoản hiện c&oacute;,&nbsp;v&igrave; bất k&igrave; l&iacute; do g&igrave;,&nbsp;theo quyết định ri&ecirc;ng của ch&uacute;ng t&ocirc;i.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><strong>b.</strong>Bạn phải từ 18 tuổi để đăng k&iacute; sử dụng dịch vụ.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>c</strong>.Bạn x&aacute;c nhận rằng e-Gate sẽ sử dụng địa chỉ email bạn cung cấp khi mở t&agrave;i khoản hoặc do bạn cập nhật theo thời gian l&agrave;m phương tiện li&ecirc;n lạc ch&iacute;nh.&nbsp;Bạn phải gi&aacute;m s&aacute;t địa chỉ email do ch&iacute;nh bạn cung cấp cho e-Gate v&agrave; email ch&iacute;nh của bạn c&oacute; khả năng gửi v&agrave; nhận thư.&nbsp;Th&ocirc;ng tin li&ecirc;n lạc qua email của bạn với e-Gate chỉ c&oacute; thể được x&aacute;c thực nếu ch&uacute;ng đến từ địa chỉ email bạn cung cấp.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>d.</strong>Bạn chịu tr&aacute;ch nhiệm bảo vệ mật khẩu của bạn an to&agrave;n.&nbsp;e-Gate kh&ocirc;ng thể v&agrave; sẽ kh&ocirc;ng chịu tr&aacute;ch nhiệm về bất k&igrave; tổn thất hoặc thiệt hại n&agrave;o do bạn kh&ocirc;ng duy tr&igrave; t&iacute;nh bảo mật cho t&agrave;i khoản v&agrave; mật khẩu của m&igrave;nh.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>e</strong>.Hỗ trợ kĩ thuật về dịch vụ chỉ được cung cấp cho người d&ugrave;ng e-Gate.&nbsp;C&aacute;c c&acirc;u hỏi về điều khoản dịch vụ sẽ được gửi đến bộ phận hỗ trợ của e-Gate.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>f.</strong>Bạn đồng &yacute; kh&ocirc;ng ph&aacute; vỡ bất k&igrave; giới hạn kĩ thuật n&agrave;o của dịch vụ,&nbsp;sử dụng bất k&igrave; c&ocirc;ng cụ n&agrave;o để k&iacute;ch hoạt c&aacute;c t&iacute;nh năng hoặc chức năng v&ocirc; hiệu h&oacute;a trong dịch vụ,&nbsp;hoặc th&aacute;o rời c&aacute;c chi tiết phần cứng đi k&egrave;m.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><strong>g.</strong>Bạn đồng &yacute; kh&ocirc;ng truy cập v&agrave;o dịch vụ hoặc gi&aacute;m s&aacute;t bất k&igrave; th&ocirc;ng tin hoặc t&agrave;i liệu nhạy cảm trong hệ thống n&agrave;o th&ocirc;ng qua bất k&igrave; robot,&nbsp;m&aacute;y qu&eacute;t,&hellip;hoặc c&aacute;c phương tiện kh&aacute;c.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><strong>NGHĨA L&Agrave;:</strong></p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Bạn chịu tr&aacute;ch nhiệm về t&agrave;i khoản của m&igrave;nh,&nbsp;th&ocirc;ng tin bạn tải l&ecirc;n e-Gate.&nbsp;Nếu bạn vi phạm điều khoản dịch vụ của e-Gate,&nbsp;ch&uacute;ng t&ocirc;i c&oacute; thể hủy quyền truy cập dịch vụ của bạn.&nbsp;Nếu cần li&ecirc;n hệ với bạn,&nbsp;ch&uacute;ng t&ocirc;i sẽ li&ecirc;n lạc qua địa chỉ email ch&iacute;nh.</p>
          <p><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;'><br>&nbsp;</span></p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><strong><span style="font-size:19px;line-height:107%;color:#2F5496;">&nbsp;</span></strong></p>
          <h2 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:19px;font-family:"Times New Roman",serif;color:#2F5496;'>2<span style='font-family:"Times New Roman",serif;color:#2F5496;font-weight:bold;'><span style="font-weight:normal;">.</span>K&iacute;ch hoạt t&agrave;i khoản:</span></h2>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Người đăng k&iacute; dịch vụ bằng c&aacute;ch mở t&agrave;i khoản sẽ l&agrave; b&ecirc;n k&yacute; hợp đồng cho c&aacute;c mục đ&iacute;ch của Điều khoản dịch vụ của ch&uacute;ng t&ocirc;i v&agrave; sẽ l&agrave; người được ph&eacute;p sử dụng bất kỳ c&aacute;c tiện &iacute;ch n&agrave;o tương ứng m&agrave; ch&uacute;ng t&ocirc;i c&oacute; thể cung cấp cho người d&ugrave;ng cuối.</p>
          <p><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;'><br>&nbsp;</span></p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <h2 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:19px;font-family:"Times New Roman",serif;color:#2F5496;'>3<span style='font-family:"Times New Roman",serif;color:#2F5496;font-weight:bold;'><span style="font-weight:normal;">.</span>Quyền hạn của e-Gate:</span></h2>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>a.</strong>Dịch vụ của ch&uacute;ng t&ocirc;i c&oacute; một loạt c&aacute;c chức năng v&agrave; t&iacute;nh năng.&nbsp;Kh&ocirc;ng phải l&uacute;c n&agrave;o tất cả c&aacute;c dịch vụ hoặc t&iacute;nh năng đều c&oacute; sẵn cho tất cả.&nbsp;Ngoại trừ trường hợp bị cấm theo luật ph&aacute;p hiện h&agrave;nh của Việt Nam,&nbsp;ch&uacute;ng t&ocirc;i c&oacute; quyền sửa đổi dịch vụ hoặc bất k&igrave; phần n&agrave;o của dịch vụ v&igrave; bất k&igrave; l&iacute; do g&igrave;,&nbsp;nhưng mọi thay đổi đều sẽ được th&ocirc;ng b&aacute;o tới bạn.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>b.</strong>e-Gate kh&ocirc;ng s&agrave;ng lọc trước c&aacute;c th&ocirc;ng tin do bạn cập nhật v&agrave; ch&uacute;ng t&ocirc;i c&oacute; quyền quyết định từ chối hoặc loại bỏ bất k&igrave; th&ocirc;ng tin n&agrave;o bất k&igrave; của bạn khỏi nền tảng trong trường hợp những th&ocirc;ng tin đ&oacute; kh&ocirc;ng hợp lệ</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>c.</strong>Mọi sự đe dọa bằng lời n&oacute;i hoặc văn bản dưới bất k&igrave; h&igrave;nh thức n&agrave;o đối với bất k&igrave; nh&acirc;n vi&ecirc;n,&nbsp;th&agrave;nh vi&ecirc;n hoặc người&nbsp;vận h&agrave;nh của e-Gate sẽ dẫn đến vi&ecirc;c chấm dứt t&agrave;i khoản ngay lập tức.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>d</strong>.Trong trường hợp c&oacute; tranh chấp về quyền sở hữu t&agrave;i khoản,&nbsp;ch&uacute;ng t&ocirc;i c&oacute; quyền y&ecirc;u cầu cung cấp th&ocirc;ng tin t&agrave;i liệu để x&aacute;c định hoặc x&aacute;c nhận quyền sở hữu t&agrave;i khoản.&nbsp;Th&ocirc;ng tin bao gồm,&nbsp;nhưng kh&ocirc;ng giới hạn,&nbsp;bản sao giấy tờ t&ugrave;y th&acirc;n do ch&iacute;nh phủ cấp,&nbsp;bốn chữ số cuối c&ugrave;ng của thẻ t&iacute;n dụng trong hồ sơ,&hellip;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>e.</strong>e-Gate c&oacute; quyền x&aacute;c định,&nbsp;theo quyết định ri&ecirc;ng của ch&uacute;ng t&ocirc;i,&nbsp;quyền sở hữu t&agrave;i khoản hợp ph&aacute;p v&agrave; chuyển t&agrave;i khoản cho ch&iacute;nh chủ hợp ph&aacute;p.&nbsp;Nếu ch&uacute;ng t&ocirc;i kh&ocirc;ng thể x&aacute;c định một c&aacute;ch hợp l&iacute; chủ t&agrave;i khoản hợp ph&aacute;p m&agrave; kh&ocirc;ng ảnh hưởng đến c&aacute;c quyền v&agrave; biện ph&aacute;p khắc phục kh&aacute;c của ch&uacute;ng t&ocirc;i,&nbsp;e-Gate c&oacute; quyền đ&igrave;nh chỉ tạm thời hoặc v&ocirc; hiệu h&oacute;a t&agrave;i khoản cho đến khi giải quyết được giữa c&aacute;c b&ecirc;n tranh chấp.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><strong>NGHĨA L&Agrave;</strong>:</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>e-Gate c&oacute; quyền kiểm so&aacute;t những người m&agrave; ch&uacute;ng t&ocirc;i cung cấp dịch vụ v&agrave; c&oacute; thể sửa đổi ch&uacute;ng bất k&igrave; l&uacute;c n&agrave;o.&nbsp;Ch&uacute;ng t&ocirc;i c&oacute; quyền từ chối phục vụ đối vơi c&aacute;c kh&aacute;ch h&agrave;ng đang vướng mắc v&agrave;o c&aacute;c rắc rối ph&aacute;p l&iacute;.&nbsp;Trong trường hợp c&oacute; tranh chấp về quyền sở hữu đối với t&agrave;i khoản e-Gate,&nbsp;ch&uacute;ng t&ocirc;i c&oacute; thể đ&oacute;ng băng t&agrave;i khoản hoặc chuyển n&oacute; cho chủ sở hữu hợp ph&aacute;p,&nbsp;theo quyết định của ch&uacute;ng t&ocirc;i.</p>
          <p><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;'><br>&nbsp;</span></p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <h2 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:19px;font-family:"Times New Roman",serif;color:#2F5496;'>4.Tr&aacute;ch nhiệm của bạn:</h2>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>a.</strong>Bạn x&aacute;c nhận v&agrave; đồng &yacute; cung cấp th&ocirc;ng tin li&ecirc;n hệ c&ocirc;ng khai,&nbsp;ch&iacute;nh s&aacute;ch ho&agrave;n tiền v&agrave; tiến tr&igrave;nh ho&agrave;n th&agrave;nh đơn h&agrave;ng tr&ecirc;n nền tảng e-Gate.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>b.</strong>Bạn x&aacute;c nhận v&agrave; đồng &yacute; sẽ kh&ocirc;ng sử dụng dịch vụ e-Gate cho bất k&igrave; mục đ&iacute;ch bất hợp ph&aacute;p hoặc tr&aacute;i ph&eacute;p n&agrave;o cũng như khi sử dụng dịch vụ,&nbsp;bạn kh&ocirc;ng được vi phạm bất k&igrave; luật n&agrave;o trong bộ luật hiện h&agrave;nh của Việt Nam.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>c.</strong>Điều khoản API chi phối quyền truy cập v&agrave; sử dụng API e-Gate của bạn.&nbsp;Bạn ho&agrave;n to&agrave;n chịu tr&aacute;ch nhiệm về hoạt động xảy ra bằng th&ocirc;ng tin đăng nhập API của m&igrave;nh v&agrave; giữ an to&agrave;n cho th&ocirc;ng tin đăng nhập API của bạn.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><strong>C&Oacute; NGHĨA L&Agrave;</strong> :</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Bạn chịu tr&aacute;ch nhiệm về t&agrave;i khoản e-Gate,&nbsp;mọi trao đổi v&agrave; th&ocirc;ng tin v&agrave; mối quan hệ của bạn đối với c&aacute;c đối t&aacute;c kh&aacute;c chứ kh&ocirc;ng phải ch&uacute;ng t&ocirc;i.&nbsp;Nếu bạn truy cập API e-Gate,&nbsp;việc sử dụng API e-Gate của bạn phải tu&acirc;n thủ theo điều khoản API.</p>
          <p><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;'><br>&nbsp;</span></p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <h2 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:19px;font-family:"Times New Roman",serif;color:#2F5496;'>5.Thanh to&aacute;n ph&iacute; v&agrave; thuế:</h2>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>a.</strong>Bạn sẽ thanh to&aacute;n c&aacute;c khoản ph&iacute; &aacute;p dụng cho đăng k&iacute; dịch vụ trực tuyến v&agrave; ph&iacute; dịch vụ thiết bị IOT,&nbsp;ph&iacute; vận chuyển.&nbsp;Bạn phải giữ một phương thức thanh to&aacute;n hợp lệ trong hồ sơ cho ch&uacute;ng t&ocirc;i để thanh to&aacute;n tất cả c&aacute;c khoản Ph&iacute; ph&aacute;t sinh định k&igrave;.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>b.</strong>Chi ph&iacute; được thanh to&aacute;n trước v&agrave; sẽ được lập h&oacute;a đơn trong khoảng thời gian 30 ng&agrave;y.&nbsp;Chi ph&iacute; sẽ xuất hiện tr&ecirc;n h&oacute;a đơn v&agrave; sẽ được gửi đến bạn qua địa chỉ email ch&iacute;nh được cung cấp.&nbsp;Đồng thời h&oacute;a đơn sẽ xuất hiện tr&ecirc;n trang t&agrave;i khoản của bảng điều khiển quản trị.&nbsp;Người d&ugrave;ng sẽ c&oacute; khoảng 2 tuần để tr&igrave;nh b&agrave;y v&agrave; giải quyết mọi vấn đề với việc thanh to&aacute;n c&aacute;c chi ph&iacute;.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>c.</strong>Nếu ch&uacute;ng t&ocirc;i kh&ocirc;ng thể xử l&yacute; thanh to&aacute;n ph&iacute; bằng phương thức thanh to&aacute;n được ủy quyền,&nbsp;ch&uacute;ng t&ocirc;i sẽ nỗ lực xử l&yacute; thanh to&aacute;n bằng phương thức thanh to&aacute;n thứ hai được ủy quyền,&nbsp;thường l&agrave; sau 14 ng&agrave;y,&nbsp;nhưng e-Gate c&oacute; thể cố&nbsp;gắng sớm hơn.&nbsp;Nếu lần thứ hai kh&ocirc;ng th&agrave;nh c&ocirc;ng,&nbsp;ch&uacute;ng t&ocirc;i sẽ thực hiện lần cuối c&ugrave;ng v&agrave; cũng k&eacute;o d&agrave;i khoảng 14 ng&agrave;y.&nbsp;Nếu nỗ lực cuối c&ugrave;ng của ch&uacute;ng t&ocirc;i kh&ocirc;ng th&agrave;nh c&ocirc;ng,&nbsp;ch&uacute;ng t&ocirc;i c&oacute; thể tạm ngừng v&agrave; thu hồi quyền truy cập v&agrave;o t&agrave;i khoản v&agrave; dịch vụ của bạn.&nbsp;T&agrave;i khoản của bạn sẽ được k&iacute;ch hoạt lại khi bạn thanh to&aacute;n mọi khoản ph&iacute; chưa thanh to&aacute;n.&nbsp;Nếu sau 60 ng&agrave;y c&aacute;c khoản ph&iacute; chưa được thanh to&aacute;n th&igrave; e-Gate c&oacute; quyền chấm dứt t&agrave;i khoản của bạn.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>d.</strong>Bạn chịu tr&aacute;ch nhiệm đối với tất cả c&aacute;c loại thuế hiện h&agrave;nh ph&aacute;t sinh từ việc bạn đăng k&iacute; sử dụng c&aacute;c sản phẩm v&agrave; dịch vụ của e-Gate.&nbsp;Trong phạm vi e-Gate t&iacute;nh c&aacute;c khoản thuế n&agrave;y,&nbsp;ch&uacute;ng được t&iacute;nh bằng thuế suất &aacute;p dụng dựa tr&ecirc;n địa chỉ thanh to&aacute;n m&agrave; bạn cung cấp cho ch&uacute;ng t&ocirc;i.&nbsp;Số tiền như vậy sẽ được bổ sung v&agrave;o Ph&iacute; cho c&aacute;c sản phẩm v&agrave; dịch vụ m&agrave; bạn đăng k&iacute; v&agrave; sẽ được lập h&oacute;a đơn cho phương thức thanh to&aacute;n được ủy quyền của bạn.&nbsp;Nếu bạn được miễn nộp c&aacute;c loại thuế như vậy,&nbsp;bạn phải cung cấp cho ch&uacute;ng t&ocirc;i bằng chứng về việc bạn được miễn,&nbsp;trong một số khu vực ph&aacute;p l&yacute; bao gồm giấy chứng nhận gốc đ&aacute;p ứng c&aacute;c y&ecirc;u cầu ph&aacute;p l&yacute; hiện h&agrave;nh chứng thực trạng th&aacute;i được miễn thuế.&nbsp;Việc miễn thuế sẽ được &aacute;p dụng từ ng&agrave;y ch&uacute;ng t&ocirc;i nhận được bằng chứng thỏa đ&aacute;ng để e-Gate miễn trừ cho bạn.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>e.</strong> Để tr&aacute;nh nghi ngờ,&nbsp;tất cả c&aacute;c khoản tiền bạn phải trả cho e-Gate theo điều khoản dịch vụ n&agrave;y sẽ được thanh to&aacute;n miễn ph&iacute; v&agrave; kh&ocirc;ng c&oacute; bất k&igrave; khoản khấu trừ n&agrave;o.&nbsp;Ngo&agrave;i ra khoản Thuế do e-Gate t&iacute;nh v&agrave; nộp thay bạn cho cơ quan thuế th&iacute;ch hợp,&nbsp;bất k&igrave; khoản khấu trừ n&agrave;o theo quy định của ph&aacute;p luật sẽ do bạn chịu v&agrave; thanh to&aacute;n ri&ecirc;ng cho cơ quan thuế li&ecirc;n quan.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>f.</strong>Bạn phải duy tr&igrave; một vị tr&iacute; ch&iacute;nh x&aacute;c trong bảng điều khiển quản trị cua t&agrave;i khoản e-Gate của m&igrave;nh.&nbsp;Nếu bạn thay đổi khu vực ph&aacute;p l&yacute;,&nbsp;bạn phải cập nhật nhanh ch&oacute;ng vị tr&iacute; của m&igrave;nh trong bảng điều khiển quản trị.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><strong>g.</strong>e-Gate kh&ocirc;ng ho&agrave;n lại tiền.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><strong>C&Oacute; NGHĨA L&Agrave;:</strong></p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Phương thức thanh to&aacute;n hợp lệ (như thẻ t&iacute;n dụng) phải được lưu trong hồ sơ để thanh to&aacute;n tất cả chi ph&iacute; dịch vụ v&agrave; phần cứng,&nbsp;vận chuyển.&nbsp;Bạn sẽ được lập h&oacute;a đơn về khoản chi ph&iacute; n&agrave;y trong v&ograve;ng 30 ng&agrave;y.&nbsp;Nếu ch&uacute;ng t&ocirc;i kh&ocirc;ng thể xử l&yacute; thanh to&aacute;n ph&iacute; bằng phương thức thanh to&aacute;n của bạn,&nbsp;ch&uacute;ng t&ocirc;i sẽ thử lại sau 14 ng&agrave;y (hoặc sớm hơn).&nbsp;Nếu ch&uacute;ng t&ocirc;i kh&ocirc;ng thể xử l&yacute; việc thanh to&aacute;n ph&iacute; của bạn trong lần thử thứ 2,&nbsp;ch&uacute;ng t&ocirc;i sẽ thực hiện lần cuối sau 14 ng&agrave;y (hoặc sớm hơn).&nbsp;Nếu thanh to&aacute;n ph&iacute; kh&ocirc;ng th&agrave;nh c&ocirc;ng trong lần n&agrave;y nữa th&igrave; e-Gate c&oacute; thể đ&oacute;ng băng t&agrave;i khoản của bạn.&nbsp;Bạn chịu tr&aacute;ch nhiệm về tất cả c&aacute;c loại thuế li&ecirc;n quan đến việc sử dụng dịch vụ.&nbsp;Kh&ocirc;ng ho&agrave;n lại tiền.</p>
          <p><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;'><br>&nbsp;</span></p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <h2 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:19px;font-family:"Times New Roman",serif;color:#2F5496;'>6.Bảo mật :</h2>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>a.</strong>&rdquo;Th&ocirc;ng tin cần bảo mật&rdquo; sẽ bao gồm th&ocirc;ng tin li&ecirc;n quan đến nh&acirc;n th&acirc;n,&nbsp;chi tiết về phương thức thanh to&aacute;n,&nbsp;lịch sử giao dịch của bạn.&nbsp;Th&ocirc;ng tin b&iacute; mật của e-Gate bao gồm tất cả c&aacute;c th&ocirc;ng tin li&ecirc;n quan đến quy tr&igrave;nh v&agrave; thực tiễn bảo mật của ch&uacute;ng th&ocirc;i.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>b.</strong>Mỗi b&ecirc;n đồng &yacute; chỉ sử dụng th&ocirc;ng tin cần bảo mật của b&ecirc;n kia khi cần thiết để thực hiện nghĩa vụ của m&igrave;nh theo Điều khoản dịch vụ v&agrave; ph&ugrave; hợp với bất k&igrave; nghĩa vụ n&agrave;o kh&aacute;c trong quy chế bảo mật.&nbsp;Mỗi b&ecirc;n đồng &yacute; rằng sẽ thực hiện tất cả c&aacute;c bước hợp l&iacute;,&nbsp;&iacute;t nhất về cơ bản tương đương c&aacute;c bước cần thực hiện để bảo vệ th&ocirc;ng tin độc quyền của ch&iacute;nh m&igrave;nh,&nbsp;để ngăn chặn việc sao ch&eacute;p,&nbsp;tiết lộ hoặc sử dụng bất k&igrave; th&ocirc;ng tin cần bảo mật n&agrave;o như vậy.&nbsp;Th&ocirc;ng tin cần bảo mật sẽ kh&ocirc;ng bao gồm bất k&igrave; th&ocirc;ng tin n&agrave;o m&agrave; b&ecirc;n nhận c&oacute; thể chứng minh:(1) đ&atilde; thuộc phạm vi c&ocirc;ng cộng,&nbsp;hoặc đ&atilde; được biết hoặc thuộc quyền sở hữu của b&ecirc;n nhận,&nbsp;tại thời điểm tiết lộ th&ocirc;ng tin đ&oacute;.;(2) được ph&aacute;t triển độc lập bởi b&ecirc;n nhận m&agrave; kh&ocirc;ng sử dụng hoặc tham chiếu đến th&ocirc;ng tin b&iacute; mật của b&ecirc;n kia v&agrave; kh&ocirc;ng vi phạm bất k&igrave; quy định n&agrave;o của Điều khoản dịch vụ n&agrave;y;hoặc (3) sau đ&oacute; b&ecirc;n thu thập một c&aacute;ch hợp ph&aacute;p từ một nguồn kh&ocirc;ng phải l&agrave; b&ecirc;n tiết lộ m&agrave; ho&agrave;n to&agrave;n ph&ugrave; hợp với Điều khoản dịch vụ n&agrave;y.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><strong>C&Oacute; NGHĨA L&Agrave;:</strong></p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Cả bạn v&agrave; e-Gate đồng &yacute; chỉ sử dụng th&ocirc;ng tin b&iacute; mật của b&ecirc;n c&ograve;n lại để thực hiện c&aacute;c nghĩa vụ trong Điều khoản dịch vụ n&agrave;y.&nbsp;Th&ocirc;ng tin b&iacute; mật phải được bảo vệ v&agrave; t&ocirc;n trọng.</p>
          <p><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;'><br>&nbsp;</span></p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <h2 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:19px;font-family:"Times New Roman",serif;color:#2F5496;'>7.Giới hạn tr&aacute;ch nhiệm v&agrave; bồi thường:</h2>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>a.</strong>Bạn hiểu r&otilde; v&agrave; đồng &yacute; rằng,&nbsp;trong phạm vi được cho ph&eacute;p theo luật hiện h&agrave;nh,&nbsp;e-Gate v&agrave; c&aacute;c nh&agrave; cung cấp của e-Gate sẽ kh&ocirc;ng chịu tr&aacute;ch nhiệm ph&aacute;p l&iacute; đối với bất k&igrave; thiệt hại trực tiếp,&nbsp;gi&aacute;n tiếp,&nbsp;ngẫu nhi&ecirc;n n&agrave;o khi bạn kh&ocirc;ng tu&acirc;n thủ c&aacute;c quy định trong Điều khoản dịch vụ.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>b.</strong>Bạn sẽ chịu tr&aacute;ch nhiệm cho bất k&igrave; vi phạm Điều khoản dịch vụ n&agrave;o của c&aacute;c chi nh&aacute;nh,&nbsp;đại l&iacute; hoặc nh&agrave; thầu phụ của bạn v&agrave; sẽ chịu tr&aacute;ch nhiệm ph&aacute;p l&yacute; như thể bạn vi phạm.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>c.</strong>Việc sử dụng dịch vụ của bạn l&agrave; rủi ro duy nhất của bạn.&nbsp;Dịch vụ được cung cấp tr&ecirc;n cơ sở &ldquo; nguy&ecirc;n trạng&rdquo; v&agrave; &lsquo;sẵn c&oacute;&rdquo;.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>d.</strong>e-Gate kh&ocirc;ng đảm bảo rằng Dịch vụ sẽ kh&ocirc;ng bị gi&aacute;n đoạn tạm thời hoặc kh&ocirc;ng ph&aacute;t sinh lỗi trong qu&aacute; tr&igrave;nh vận h&agrave;nh.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>e.</strong>e-Gate kh&ocirc;ng đảm bảo rằng c&aacute;c kết quả c&oacute; thể nhận được từ việc sử dụng dịch vụ sẽ ch&iacute;nh x&aacute;c hoặc đ&aacute;ng tin cậy ho&agrave;n to&agrave;n.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>f.</strong>e-Gate kh&ocirc;ng chịu tr&aacute;ch nhiệm về bất k&igrave; nghĩa vụ hoặc nghĩa vụ thuế của bạn li&ecirc;n quan đến sử dụng dịch của ch&uacute;ng t&ocirc;i.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>h.</strong>e-Gate kh&ocirc;ng đảm bảo rằng chất lượng của bất k&igrave; sản phẩm,&nbsp;dịch vụ hoặc th&ocirc;ng tin n&agrave;o kh&aacute;c m&agrave; bạn mua hoặc c&oacute; được th&ocirc;ng qua dịch vụ của ch&uacute;ng t&ocirc;i sẽ đ&aacute;p ứng mong đợi của bạn hoặc bất k&igrave; lỗi n&agrave;o trong Dịch vụ sẽ được sửa chữa ngay lập tức.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><strong>C&Oacute; NGHĨA L&Agrave;</strong>:</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Ch&uacute;ng t&ocirc;i kh&ocirc;ng chịu tr&aacute;ch nhiệm về c&aacute;c thiệt hại hoặc c&aacute;c vụ kiện ph&aacute;t sinh nếu bạn vi phạm ph&aacute;p luật sở tại,&nbsp;vi phạm thỏa thuận n&agrave;y hoặc đi ngược lại c&aacute;c quyền v&agrave; nghĩa vụ của b&ecirc;n thứ ba.&nbsp;Dịch vụ được cung cấp tr&ecirc;n cơ sở &ldquo;nguy&ecirc;n trạng&rdquo; v&agrave; &ldquo;sẵn c&oacute;&rdquo;.&nbsp;Ch&uacute;ng t&ocirc;i kh&ocirc;ng cung cấp bảo h&agrave;nh v&agrave; tr&aacute;ch nhiệm của ch&uacute;ng t&ocirc;i bị giới hạn trong trường hợp c&oacute; sai s&oacute;t hoặc gi&aacute;n đoạn.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Nếu bạn hoặc kh&aacute;ch h&agrave;ng biết hoặc nghi ngờ bất k&igrave; vi phạm n&agrave;o đối với Y&ecirc;u cầu dịch vụ email,vui l&ograve;ng th&ocirc;ng b&aacute;o cho e-Gate theo địa chỉ sau <strong>info@ing.vn</strong><strong>,&nbsp;</strong>e-Gate<strong>&nbsp;</strong>sẽ quyết định việc tu&acirc;n thủ c&aacute;c y&ecirc;u cầu về dịch vụ email theo quyết định của m&igrave;nh</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><strong>C&Oacute; NGHĨA L&Agrave;</strong> :</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Bằng việc sử dụng dịch vụ email,bạn đồng &yacute; rằng e-Gate c&oacute; thể sử dụng một số c&ocirc;ng cụ nhất định để đảm bảo nội dung của c&aacute;c email được gửi qua dịch vụ l&agrave; an to&agrave;n v&agrave; tu&acirc;n thủ theo c&aacute;c ch&iacute;nh s&aacute;ch của ch&uacute;ng t&ocirc;i</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><strong>b.</strong>Dịch vụ của b&ecirc;n thứ ba :</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Đ&ocirc;i khi,&nbsp;e-Gate c&oacute; thể đề xuất,&nbsp;cung cấp cho bạn quyền truy cập hoặc k&iacute;ch hoạt phần mềm,&nbsp;ứng dụng của b&ecirc;n thứ ba (&ldquo;Apps&rdquo;),&nbsp;sản phẩm,&nbsp;dịch vụ hoặc li&ecirc;n kết trang web(gọi chung l&agrave; Dịch vụ của b&ecirc;n thứ ba) để bạn xem x&eacute;t hoặc sử dụng.&nbsp;Như vậy dịch vụ của b&ecirc;n thứ ba chỉ được cung cấp để tạo sự thuận tiện cho bạn v&agrave; việc bạn mua,&nbsp;truy cập hoặc sử dụng bất k&igrave; Dịch vụ của b&ecirc;n thứ ba n&agrave;o l&agrave; việc chỉ li&ecirc;n quan đến bạn v&agrave; b&ecirc;n thứ ba.&nbsp;Ngo&agrave;i c&aacute;c điều khoản dịch vụ n&agrave;y,&nbsp;bạn cũng đồng &yacute; bị r&agrave;ng buộc bởi c&aacute;c điều khoản bổ sung d&agrave;nh ri&ecirc;ng cho dịch vụ &aacute;p dụng cho c&aacute;c dịch vụ m&agrave; bạn mua hoặc được cung cấp bởi nh&agrave; cung cấp thứ ba.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Bất k&igrave; hoạt động sử dụng n&agrave;o của bạn đối với Dịch vụ của b&ecirc;n thứ ba được cung cấp th&ocirc;ng qua e-Gate ho&agrave;n to&agrave;n do bạn tự chịu rủi ro v&agrave; to&agrave;n quyền quyết định v&agrave; bạn phải c&oacute; tr&aacute;ch nhiệm đọc c&aacute;c điều khoản v&agrave; điều kiện hoặc ch&iacute;nh s&aacute;ch bảo mật &aacute;p dụng cho b&ecirc;n thứ ba trước khi bắt đầu sử dụng.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Ch&uacute;ng t&ocirc;i kh&ocirc;ng cung cấp bất k&igrave; bảo đảm hoặc đại diện ph&aacute;p l&iacute; n&agrave;o cho bạn đối với Dịch vụ của b&ecirc;n thứ ba.&nbsp;Bạn phải hiểu r&otilde; rằng e-Gate kh&ocirc;ng c&oacute; quyền kiểm so&aacute;t đối với Dịch vụ b&ecirc;n thứ ba v&agrave; sẽ kh&ocirc;ng chịu tr&aacute;ch nhiệm hoặc nghĩa vụ ph&aacute;p l&yacute; đối với bạn hoặc bất k&igrave; ai kh&aacute;c khi sử dụng Dịch vụ của b&ecirc;n thứ ba đ&oacute;.&nbsp;e-Gate kh&ocirc;ng chịu tr&aacute;ch nhiệm hoặc nghĩa vụ ph&aacute;p l&iacute; với bất k&igrave; ai về việc ngừng hoặc đ&igrave;nh chỉ quyền truy cập hoặc v&ocirc; hiệu h&oacute;a bất k&igrave; dịch vụ n&agrave;o của b&ecirc;n thứ ba.&nbsp;e-Gate thực sự khuy&ecirc;n bạn n&ecirc;n t&igrave;m kiếm sự tư vấn của chuy&ecirc;n gia trước khi sử dụng Dịch vụ của b&ecirc;n thư ba để đảm bảo ch&uacute;ng c&oacute; thể đ&aacute;p ứng nhu cầu của bạn.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Nếu bạn c&agrave;i đặt hoặc bật Dịch vụ của b&ecirc;n thứ ba để sử dụng ,&nbsp;bạn cấp cho ch&uacute;ng t&ocirc;i quyền cho ph&eacute;p Nh&agrave; cung cấp b&ecirc;n thứ ba hiện h&agrave;nh truy cập v&agrave;o dữ liệu v&agrave; c&aacute;c th&ocirc;ng tin kh&aacute;c của bạn v&agrave; thực hiện bất k&igrave; h&agrave;nh động n&agrave;o kh&aacute;c theo y&ecirc;u cầu của Dịch vụ b&ecirc;n thứ ba.&nbsp;e-Gate kh&ocirc;ng chịu tr&aacute;ch nhiệm về bất k&igrave; tiết lộ,&nbsp;sửa đổi hoặc x&oacute;a dữ liệu của bạn,&nbsp;hoặc đối với bất k&igrave; tổn thất,&nbsp;thiệt hại tương ứng n&agrave;o m&agrave; bạn phải chịu do việc Dịch vụ b&ecirc;n thứ ba truy cập v&agrave;o dữ liệu v&agrave; th&ocirc;ng tin của bạn.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Mối li&ecirc;n hệ giữa bạn v&agrave; bất k&igrave; Nh&agrave; cung cấp b&ecirc;n thứ ba n&agrave;o ho&agrave;n to&agrave;n l&agrave; giữa bạn v&agrave; Nh&agrave; cung cấp b&ecirc;n thứ ba đ&oacute;,&nbsp;e-Gate kh&ocirc;ng c&oacute; nghĩa vụ can thiệp v&agrave;o bất k&igrave; tranh chấp n&agrave;o ph&aacute;t sinh giữa bạn v&agrave; Nh&agrave; cung cấp b&ecirc;n thứ ba đ&oacute;,&nbsp;cũng như chịu tr&aacute;ch nhiệm ph&aacute;p l&iacute; đối với bất k&igrave; thiệt hại (trực tiếp,gi&aacute;n tiếp,ngẫu nhi&ecirc;n&hellip;) do bất k&igrave; dịch vụ n&agrave;o của b&ecirc;n thứ ba.&nbsp;Những giới hạn n&agrave;y sẽ được &aacute;p dụng ngay cả khi e-Gate đ&atilde; được th&ocirc;ng b&aacute;o về khả năng xảy ra những thiệt hại như vậy.&nbsp;C&aacute;c giới hạn n&ecirc;u tr&ecirc;n sẽ được &aacute;p dụng trong phạm vi tối đa m&agrave; luật ph&aacute;p hiện h&agrave;nh cho ph&eacute;p.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><strong>C&Oacute; NGHĨA L&Agrave;</strong> :</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Ch&uacute;ng t&ocirc;i kh&ocirc;ng chịu tr&aacute;ch nhiệm về c&aacute;c dịch vụ của b&ecirc;n thứ ba, v&igrave; vậy bạn c&oacute; thể tự chịu rủi ro khi sử dụng ch&uacute;ng. Nếu bạn chọn sử dụng dịch vụ của b&ecirc;n thứ ba tr&ecirc;n nền tảng e-Gate, bạn đồng &yacute; cho ch&uacute;ng t&ocirc;i chia sẻ dữ liệu v&agrave; th&ocirc;ng tin của bạn với c&aacute;c dịch vụ đ&oacute;. Nếu bạn sử dụng dịch vụ của b&ecirc;n thứ ba, bạn đồng &yacute; rằng ch&uacute;ng t&ocirc;i kh&ocirc;ng cung cấp bảo h&agrave;nh, v&igrave; vậy h&atilde;y t&igrave;m kiếm lời khuy&ecirc;n từ c&aacute;c chuy&ecirc;n gia trước.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <h2 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:19px;font-family:"Times New Roman",serif;color:#2F5496;'>10.Phản hồi v&agrave; đ&aacute;nh gi&aacute;:</h2>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>e-Gate hoan ngh&ecirc;nh mọi &yacute; tưởng v&agrave; đề xuất li&ecirc;n quan đến cải tiến hoặc bổ sung cho c&aacute;c dịch vụ cung cấp.&nbsp;Trong bất k&igrave; trường hợp n&agrave;o sẽ kh&ocirc;ng tiết lộ bất kỳ &yacute; tưởng,&nbsp;đề xuất hoặc t&agrave;i liệu li&ecirc;n quan hoặc bất kỳ đ&aacute;nh gi&aacute; n&agrave;o về dịch của ch&uacute;ng t&ocirc;i cũng như c&aacute;c dịch vụ của b&ecirc;n thứ ba (gọi chung l&agrave; &ldquo;Phản hồi&rdquo;) theo quy tắc bảo mật th&ocirc;ng tin của e-Gate.&nbsp;Bằng c&aacute;ch gửi phản hồi đến e-Gate&nbsp;(cho d&ugrave; được gửi trực tiếp đến e-Gate hay được đăng tr&ecirc;n bất k&igrave; diễn đ&agrave;n hoặc trang n&agrave;o được lưu trữ tr&ecirc;n e-Gate),&nbsp;th&igrave; e-Gate sẽ được to&agrave;n quyền sử dụng c&aacute;c phản hồi n&agrave;y nếu muốn,&nbsp;nguy&ecirc;n trạng hoặc c&oacute; qua chỉnh sửa bởi e-Gate,&nbsp;m&agrave; kh&ocirc;ng cần bất k&igrave; sự cho ph&eacute;p n&agrave;o của bạn hoặc b&ecirc;n thứ ba.&nbsp;Mọi đ&aacute;nh gi&aacute; về dịch vụ b&ecirc;n thứ ba m&agrave; bạn gửi cho e-Gate phải ch&iacute;nh x&aacute;c theo hiểu biết của bạn v&agrave; kh&ocirc;ng được bất hợp ph&aacute;p,&nbsp;tục tĩu,&nbsp;đe dọa,&nbsp;n&oacute;i xấu,&nbsp;x&acirc;m phạm quyền sở hữu tr&iacute; tuệ hoặc g&acirc;y tổn hại cho c&aacute;c b&ecirc;n thứ ba.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><strong>C&Oacute; NGHĨA L&Agrave;</strong>:</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Ch&uacute;ng t&ocirc;i hoan ngh&ecirc;nh phản hồi của kh&aacute;ch h&agrave;ng nhưng kh&ocirc;ng c&oacute; nghĩa vụ đảm bảo rằng c&aacute;c &yacute; tưởng v&agrave; đề xuất li&ecirc;n quan đến Dịch vụ của ch&uacute;ng t&ocirc;i hoặc Dịch vụ của b&ecirc;n thứ ba vẫn được bảo mật v&agrave; ch&uacute;ng t&ocirc;i c&oacute; thể sử dụng phản hồi theo bất k&igrave; c&aacute;ch n&agrave;o m&agrave; ch&uacute;ng t&ocirc;i mong muốn.</p>
          <p><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;'><br>&nbsp;</span></p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <h2 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:19px;font-family:"Times New Roman",serif;color:#2F5496;'>11.Quyền ri&ecirc;ng tư v&agrave; bảo vệ dữ liệu:</h2>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>a.</strong>e-Gate cam kết bảo vệ sự ri&ecirc;ng tư của th&ocirc;ng tin c&aacute; nh&acirc;n của bạn.&nbsp;Bằng việc chọn sử dụng c&aacute;c dịch vụ của e-Gate cung cấp,&nbsp;bạn thừa nhận v&agrave; đồng &yacute; rằng việc thu thập,&nbsp;sử dụng v&agrave; tiết lộ th&ocirc;ng tin c&aacute; nh&acirc;n n&agrave;y của e-Gate được điều chỉnh bởi <strong>Ch&iacute;nh s&aacute;ch quyền ri&ecirc;ng tư</strong> của ch&uacute;ng t&ocirc;i.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>b.</strong>Trong <strong>Ch&iacute;nh s&aacute;ch quyền ri&ecirc;ng tư</strong> của ch&uacute;ng t&ocirc;i cũng đề cập tới c&aacute;ch thức ch&uacute;ng t&ocirc;i bảo vệ dữ liệu của bạn theo chuẩn luật ph&aacute;p của nước sở tại.</p>
          <p><strong><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;'><br>&nbsp;</span></strong></p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><strong>&nbsp;</strong></p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><strong>&nbsp;</strong></p>
          <h2 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:19px;font-family:"Times New Roman",serif;color:#2F5496;'>12.Thời hạn v&agrave; chấm dứt:</h2>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>a.</strong> Thời hạn của c&aacute;c điều khoản dịch vụ n&agrave;y sẽ bắt đầu v&agrave;o ng&agrave;y bạn ho&agrave;n tất đăng k&iacute; sử dụng Dịch vụ v&agrave; tiếp tục cho đến khi ch&uacute;ng t&ocirc;i hoặc bạn chấm dứt,theo c&aacute;c điều khoản được cung cấp b&ecirc;n dưới.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>b.</strong>Bạn c&oacute; thể hủy T&agrave;i khoản của m&igrave;nh v&agrave; chấm dứt điều khoản dịch vụ bất kỳ l&uacute;c n&agrave;o bằng c&aacute;ch li&ecirc;n hệ với bộ phận hỗ trợ của e-Gate,&nbsp;sau đ&oacute; thực hiện theo c&aacute;c hướng dẫn cụ thể được chỉ ra cho bạn trong phản hồi của e-Gate.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>c.</strong>Kh&ocirc;ng giới hạn bất kỳ biện ph&aacute;p n&agrave;o kh&aacute;c,&nbsp;ch&uacute;ng t&ocirc;i c&oacute; thể tạm ngưng hoặc chấm dứt T&agrave;i khoản của bạn hoặc Điều khoản dịch vụ v&igrave; bất kỳ l&iacute; do g&igrave; m&agrave; kh&ocirc;ng cần th&ocirc;ng b&aacute;o v&agrave; bất kỳ l&uacute;c n&agrave;o (trừ khi luật ph&aacute;p y&ecirc;u cầu ),&nbsp;bao gồm việc nếu ch&uacute;ng t&ocirc;i nghi ngờ rằng bạn đ&atilde; tham gia v&agrave;o hoạt động gian lận li&ecirc;n quan đến việc sử dụng Dịch vụ.&nbsp;Việc chấm dứt Điều khoản dịch vụ sẽ kh&ocirc;ng ảnh hưởng đến bất k&igrave; quyền hoặc nghĩa vụ n&agrave;o ph&aacute;t sinh trước ng&agrave;y chấm dứt.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>d.</strong>Khi một trong hai b&ecirc;n chấm dứt Dịch vụ v&igrave; bất cứ l&yacute; do g&igrave;:</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>e-Gate sẽ ngừng cung cấp Dịch vụ cho bạn v&agrave; bạn sẽ kh&ocirc;ng thể truy cập v&agrave;o T&agrave;i khoản của m&igrave;nh nữa.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Trừ khi c&oacute; quy định kh&aacute;c trong Điều khoản dịch vụ,&nbsp;bạn sẽ kh&ocirc;ng được hưởng bất kỳ khoản trả n&agrave;o của bất kỳ khoản Ph&iacute;,&nbsp;tỷ lệ hoặc h&igrave;nh thức kh&aacute;c;.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Bất kỳ số dư n&agrave;o chưa thanh to&aacute;n n&agrave;o c&ograve;n nợ e-Gate để bạn sử dụng dịch vụ cho đến ng&agrave;y hiệu lực của việc chấm dứt hợp đồng,&nbsp;th&igrave; bạn phải c&oacute; nghĩa vụ thanh to&aacute;n ngay lập tức cho e-Gate.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><strong>C&Oacute; NGHĨA L&Agrave;:</strong></p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Để bắt đầu chấm dứt,&nbsp;bạn phải li&ecirc;n hệ với bộ phận hỗ trợ.&nbsp;e-Gate sẽ phản hồi với th&ocirc;ng tin cụ thể về quy tr&igrave;nh chấm dứt t&agrave;i khoản của bạn.&nbsp;Sau khi việc chấm dứt được x&aacute;c nhận,&nbsp;t&agrave;i khoản của bạn sẽ bị thu hồi.&nbsp;Nếu bạn hủy hợp đồng v&agrave;o giữa chu kỳ thanh to&aacute;n,&nbsp;bạn sẽ nhận được h&oacute;a đơn cuối c&ugrave;ng th&ocirc;ng qua email.&nbsp;e-Gate c&oacute; thể chấm dứt t&agrave;i khoản của bạn bất kỳ l&uacute;c n&agrave;o.</p>
          <p><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;'><br>&nbsp;</span></p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <h2 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:19px;font-family:"Times New Roman",serif;color:#2F5496;'>13.Sửa đổi:</h2>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>a.</strong>Ch&uacute;ng t&ocirc;i c&oacute; quyền cập nhật hoặc thay đổi bất kỳ phần n&agrave;o của Điều khoản dịch vụ v&agrave;o bất kỳ l&uacute;c n&agrave;o.&nbsp;Ch&uacute;ng t&ocirc;i sẽ cung cấp cho bạn th&ocirc;ng b&aacute;o trước một c&aacute;ch hợp l&yacute; nhất về những thay đổi đối với Điều khoản sử dụng dịch vụ ảnh hưởng nghi&ecirc;m trọng đến việc sử dụng Dịch vụ của bạn hoặc quyền lợi của bạn bằng email qua địa chỉ email ch&iacute;nh,&nbsp;cung cấp th&ocirc;ng b&aacute;o qua bảng điều khiển quản trị e-Gate,&nbsp;hoặc bằng phương tiện kh&aacute;c.&nbsp;Tuy nhi&ecirc;n,&nbsp;e-Gate c&oacute; thể thực hiện c&aacute;c thay đổi g&acirc;y ảnh hưởng nghi&ecirc;m trọng đến việc sử dụng Dịch vụ của bạn hoặc c&aacute;c quyền lợi của bạn theo Điều khoản dịch vụ bất kỳ l&uacute;c n&agrave;o v&agrave; c&oacute; hiệu lực ngay lập tức(i) v&igrave; l&yacute; do ph&aacute;p l&yacute;,&nbsp;quy định,&nbsp;gian lận v&agrave; lạm dụng hoặc l&yacute; do bảo mật;hoặc (ii) để hạn chế c&aacute;c hoạt động m&agrave; ch&uacute;ng t&ocirc;i cho l&agrave; kh&ocirc;ng an to&agrave;n,&nbsp;kh&ocirc;ng ph&ugrave; hợp hoặc g&acirc;y kh&oacute; chịu.&nbsp;Trừ khi c&oacute; những th&ocirc;ng b&aacute;o kh&aacute;c của ch&uacute;ng t&ocirc;i (nếu c&oacute;),&nbsp;bất kỳ thay đổi n&agrave;o đối với Điều khoản dịch vụ sẽ c&oacute; hiệu lực ngay lập tức.&nbsp;Nếu bạn kh&ocirc;ng đồng &yacute; với Điều khoản dịch vụ đ&atilde; sửa đổi,&nbsp;bạn sẽ phải ngừng truy cập v&agrave; sử dụng Dịch vụ.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>b.</strong>e-Gate c&oacute; thể thay đổi ph&iacute; dịch vụ theo thời gian.&nbsp;Ch&uacute;ng t&ocirc;i sẽ cung cấp cho bạn th&ocirc;ng b&aacute;o trước 30 ng&agrave;y trước khi c&oacute; bất kỳ thay đổi n&agrave;o về Ph&iacute; bằng c&aacute;ch gửi email đến t&agrave;i khoản email ch&iacute;nh của bạn,&nbsp;cung cấp th&ocirc;ng qua bảng điều khiển quản trị e-Gate hoặc bằng c&aacute;c phương ti&ecirc;n tương tự.&nbsp;e-Gate sẽ kh&ocirc;ng chịu tr&aacute;ch nhiệm với bạn hoặc bất kỳ b&ecirc;n thứ ba n&agrave;o về bất kỳ sửa đổi,&nbsp;thay đổi gi&aacute;,&nbsp;tạm ngừng hoặc ngừng cung cấp Dịch vụ.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><strong>C&Oacute; NGHĨA L&Agrave;:</strong></p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Nếu ch&uacute;ng t&ocirc;i thực hiện một thay đổi quan trọng đối với Điều khoản dịch vụ,&nbsp;v&agrave; điều n&agrave;y ảnh hưởng xấu đến quyền lợi của bạn,&nbsp;ch&uacute;ng t&ocirc;i sẽ th&ocirc;ng b&aacute;o trước cho bạn ( trừ khi thay đổi li&ecirc;n quan đến c&aacute;c y&ecirc;u cầu ph&aacute;p l&yacute; hoặc để ngăn chặn sự lạm dụng Dịch vụ của ch&uacute;ng t&ocirc;i).</p>
          <p><span style='font-family:"Times New Roman",serif;color:#2F5496;font-weight:bold;'><span style="font-size:19px;line-height:107%;"><br>&nbsp;</span></span></p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><span style='font-family:"Times New Roman",serif;color:#2F5496;font-weight:bold;'><span style="font-size:19px;line-height:107%;">&nbsp;</span></span></p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><span style='font-family:"Times New Roman",serif;color:#2F5496;font-weight:bold;'><span style="font-size:19px;line-height:107%;">14. Điều kiện chung</span></span>:</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>a.</strong>Điều khoản dịch vụ,&nbsp;bao gồm c&aacute;c t&agrave;i liệu tham khảo,&nbsp;sẽ tạo th&agrave;nh một bộ thỏa thuận giữa bạn v&agrave; e-Gate.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>b.</strong>Việc e-Gate kh&ocirc;ng thực hiện hoặc thực thi bất kỳ quyền hoặc quy định n&agrave;o của Điều khoản dịch vụ sẽ kh&ocirc;ng cấu th&agrave;nh việc từ bỏ quyền hoặc quy định đ&oacute;.&nbsp;Nếu bất kỳ điều khoản n&agrave;o trong Điều khoản dịch vụ,&nbsp;bao gồm tất cả c&aacute;c điều khoản v&agrave; điều kiện v&agrave; c&aacute;c t&agrave;i liệu tham chiếu kh&aacute;c,&nbsp;bị t&ograve;a &aacute;n c&oacute; thẩm quyền cho rằng tr&aacute;i ph&aacute;p luật,&nbsp;điều khoản đ&oacute; sẽ được thay đổi v&agrave; giải th&iacute;ch để ho&agrave;n th&agrave;nh tốt nhất c&aacute;c mục ti&ecirc;u của điều khoản ban đầu trong phạm vi tối đa được ph&aacute;p luật cho ph&eacute;p.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>c.</strong>Điều khoản Dịch vụ c&oacute; thể sẵn s&agrave;ng bằng ng&ocirc;n ngữ kh&aacute;c ngo&agrave;i tiếng Việt.&nbsp;Trong phạm vi m&acirc;u thuẫn hoặc xung đột n&agrave;o giữa Điều khoản dịch vụ bằng tiếng Việt v&agrave; Điều khoản dịch vụ của e-Gate c&oacute; sẵn bằng ng&ocirc;n ngữ kh&aacute;c,&nbsp;phi&ecirc;n bản tiếng Việt mới nhất của Điều khoản dịch vụ tại <a href="http://www.e-gate.vn/terms-of-use">www.e-gate.vn/terms-of-use</a> sẽ được ưu ti&ecirc;n &aacute;p dụng.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>d.</strong>Tất cả c&aacute;c điều khoản v&agrave; quy định của Điều khoản dịch vụ sẽ r&agrave;ng buộc v&agrave; c&oacute; hiệu lực đối với lợi &iacute;ch của c&aacute;c b&ecirc;n đối với những người kế thừa,&nbsp;thừa kế,&nbsp;người được chuyển nhượng được ph&aacute;p luật&nbsp;thừa nhận&nbsp;v&agrave; đại diện hợp ph&aacute;p của họ.&nbsp;e-Gate sẽ được ph&eacute;p chuyển nhượng c&aacute;c Điều khoản dịch vụ n&agrave;y m&agrave; kh&ocirc;ng cần th&ocirc;ng b&aacute;o cho bạn hoặc sự đồng &yacute; từ bạn.&nbsp;Bạn sẽ kh&ocirc;ng c&oacute; quyền chuyển nhượng hoặc chuyển giao Điều khoản dịch vụ hoặc bất kỳ quyền hoặc nghĩa vụ n&agrave;o của bạn theo đ&acirc;y,&nbsp;cho bất kỳ b&ecirc;n thứ ba n&agrave;o m&agrave; kh&ocirc;ng c&oacute; sự đồng &yacute; trước bằng văn bản của e-Gate,&nbsp;được cung cấp hoặc giữ lại theo quyết định của e-Gate.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><strong>e.</strong>Nếu bất kỳ điều khoản (hoặc một phần của điều khoản) trong Điều khoản dịch vụ được cho l&agrave; kh&ocirc;ng hợp lệ, bất hợp ph&aacute;p hoặc kh&ocirc;ng thể thực thi ở một kh&iacute;a cạnh n&agrave;o đ&oacute;, th&igrave; điều n&agrave;y sẽ kh&ocirc;ng ảnh hưởng tới c&aacute;c điều khoản kh&aacute;c trong Điều khoản dịch vụ.</p>
          <p><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;'><br>&nbsp;</span></p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <h2 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:19px;font-family:"Times New Roman",serif;color:#2F5496;'>8.Sở hữu tr&iacute; tuệ v&agrave; th&ocirc;ng tin của bạn:</h2>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><strong>a.</strong>Sở hữu tr&iacute; tuệ:</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Bạn đồng &yacute; kh&ocirc;ng sử dụng bất kỳ nh&atilde;n hiện,&nbsp;biểu tượng hay logo của e-Gate,&nbsp;cho d&ugrave; đ&atilde; đăng k&iacute; hay chưa đăng k&iacute; trừ khi bạn được e-Gate ủy quyền bằng văn bản.&nbsp;Bạn đồng &yacute; kh&ocirc;ng sử dụng hoặc th&ocirc;ng qua bất k&igrave; nh&atilde;n hiệu n&agrave;o c&oacute; thể bị coi l&agrave; g&acirc;y nhầm lẫn với nh&atilde;n hiện e-Gate.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Bạn đồng &yacute; kh&ocirc;ng mua,&nbsp;đăng k&iacute; hoặc sử dụng c&ocirc;ng cụ t&igrave;m kiếm hoặc c&aacute;c từ kh&oacute;a trả cho mỗi nhấp chuột ( chẳng hạn như Google Ads),&nbsp;nh&atilde;n hiệu,&nbsp;địa chỉ email,&nbsp;t&ecirc;n mạng x&atilde; hội hoặc t&ecirc;n miền sử dụng hoặc bao gồm thương hiệu e-Gate hoặc e-Gate hoặc bất k&igrave; thuật ngữ n&agrave;o c&oacute; thể g&acirc;y nhầm lẫn với thương hiệu e-Gate.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><strong>b.</strong>Th&ocirc;ng tin của bạn:</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Những th&ocirc;ng tin thuộc sở hữu của bạn,&nbsp;khi bạn tải l&ecirc;n nền tảng e-Gate,&nbsp;ch&uacute;ng vẫn l&agrave; của bạn,&nbsp;t&ugrave;y thuộc v&agrave;o bất k&igrave; quyền hoặc giấy ph&eacute;p n&agrave;o được cấp trong Điều khoản v&agrave; dịch vụ ở nơi kh&aacute;c.&nbsp;Bạn c&oacute; thể x&oacute;a th&ocirc;ng tin n&agrave;y bất cứ l&uacute;c n&agrave;o bằng c&aacute;ch x&oacute;a t&agrave;i khoản tr&ecirc;n e-Gate.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Bạn đồng &yacute; rằng e-Gate c&oacute; thể,&nbsp;v&agrave; bất k&igrave; l&uacute;c n&agrave;o&nbsp;xem x&eacute;t v&agrave; x&oacute;a bất cứ hoặc tất cả th&ocirc;ng tin được gửi đến dịch vụ,&nbsp;mặc d&ugrave; e-Gate kh&ocirc;ng c&oacute; nghĩa vụ phải l&agrave;m như vậy.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><strong>C&Oacute; NGHĨA L&Agrave;</strong> :</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Mọi thứ bạn tải l&ecirc;n vẫn l&agrave; của bạn ( nếu n&oacute; thực sự thuộc về bạn) v&agrave; l&agrave; tr&aacute;ch nhiệm của bạn,&nbsp;nhưng e-Gate c&oacute; thể sử dụng v&agrave; xuất bản những thứ bạn tải l&ecirc;n.&nbsp;Mọi thứ được tải l&ecirc;n e-Gate vẫn l&agrave; t&agrave;i sản của chủ sở hữu v&agrave; tr&aacute;ch nhiệm của chủ sở hữu ban đầu.&nbsp;Tuy nhi&ecirc;n,&nbsp;e-Gate sẽ được ph&eacute;p sử dụng c&aacute;c th&ocirc;ng tin n&agrave;y để vận h&agrave;nh v&agrave; quảng b&aacute; cho dịch vụ của m&igrave;nh.</p>
          <p><span style='font-size:17px;line-height:107%;font-family:"Times New Roman",serif;'><br>&nbsp;</span></p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>&nbsp;</p>
          <h2 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:19px;font-family:"Times New Roman",serif;color:#2F5496;'>9.Dịch vụ bổ sung:</h2>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><strong>a.</strong>e-Gate email:</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Bạn c&oacute; thể tạo hoặc gửi email từ T&agrave;i khoản của m&igrave;nh bằng c&aacute;c dịch vụ email của e-Gate.&nbsp;Ngo&agrave;i c&aacute;c điều khoản &aacute;p dụng cho dịch vụ n&oacute;i chung (bao gồm ch&iacute;nh s&aacute;ch sử dụng được chấp nhận v&agrave; ch&iacute;nh s&aacute;ch quyền ri&ecirc;ng tư của e-Gate),&nbsp;c&aacute;c điều khoản sau &aacute;p dụng cho quyền truy cập v&agrave; sử dụng dịch vụ email của bạn :</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>e-Gate sử dụng một số biện ph&aacute;p kiểm so&aacute;t nhất định để qu&eacute;t nội dung email bạn gửi bằng dịch vụ email trước khi gửi.&nbsp;Việc qu&eacute;t nội dung như vậy như vậy nhằm hạn chế spam,&nbsp;lừa đảo hoặc nội dung độc hại kh&aacute;c vi phạm điều khoản dịch vụ n&agrave;y hoặc <strong>ch&iacute;nh s&aacute;ch sử dụng được chấp nhận của e-Gate.</strong><strong>&nbsp;</strong>Bằng c&aacute;ch sử dụng dịch vụ email,&nbsp;bạn cấp cho e-Gate một c&aacute;ch r&otilde; r&agrave;ng quyền sử dụng chức năng qu&eacute;t nội dung đ&oacute;.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Bằng c&aacute;ch tạo hoặc gửi email qua dịch vụ email,&nbsp;bạn đồng &yacute; tu&acirc;n thủ c&aacute;c y&ecirc;u cầu sau đ&acirc;y (<strong>C&aacute;c y&ecirc;u cầu về dịch vụ email</strong>). e-Gate hoặc c&aacute;c nh&agrave; cung cấp của b&ecirc;n thứ ba c&oacute; thể tạm ngừng hoặc chấm dứt việc truy cập sử dụng v&agrave; sử dụng dịch vụ email của bạn nếu bạn kh&ocirc;ng ph&ugrave; hợp v&oacute;i ti&ecirc;u chuẩn của dịch vụ email.</p>`,
        },
          {
          title: "Bảo mật dữ liệu khách hàng",
          text:`<h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:21px;font-family:"Times New Roman",serif;color:#2F5496;'>Dịch vụ dữ liệu kh&aacute;ch h&agrave;ng : L&agrave;m thế n&agrave;o để lưu trữ cho dữ liệu n&agrave;y linh hoạt v&agrave; an to&agrave;n</h1>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Nếu bạn l&agrave;m việc với dữ liệu kh&aacute;ch h&agrave;ng,&nbsp;lưu trữ c&aacute;c th&ocirc;ng tin mật v&agrave; nhạy cảm tr&ecirc;n m&aacute;y chủ c&ocirc;ng ty hoặc sử dụng dịch vụ của c&aacute;c nh&agrave; cung cấp dịch vụ đ&aacute;m m&acirc;y,&nbsp;th&igrave; bảo mật dữ liệu phải l&agrave; một trong những ưu ti&ecirc;n h&agrave;ng đầu của bạn.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Với số lượng c&aacute;c vụ vi phạm dữ liệu ng&agrave;y c&agrave;ng gia tăng,&nbsp;kh&aacute;ch h&agrave;ng ng&agrave;y c&agrave;ng lo lắng về t&iacute;nh bảo mật của dữ liệu c&aacute; nh&acirc;n của họ v&agrave; liệu c&aacute;c c&ocirc;ng ty họ sử dụng dịch vụ c&oacute; thực sự bảo mật được dữ liệu đ&oacute; hay kh&ocirc;ng?&nbsp;V&igrave; thế,&nbsp;việc x&acirc;y dựng c&aacute;c chiến lược hiệu quả l&agrave; cần thiết để vượt qua được mối đe dọa n&agrave;y.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Ch&uacute;ng t&ocirc;i &aacute;p&nbsp;dụng một số c&aacute;ch được cho l&agrave; suy nghĩ to&agrave;n diện nhất để giữ cho dữ liệu dịch vụ kh&aacute;ch h&agrave;ng lu&ocirc;n an to&agrave;n v&agrave; linh hoạt:</p>
          <h2 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:19px;font-family:"Times New Roman",serif;color:#2F5496;'>1.N&acirc;ng cấp phần mềm bảo mật của bạn:</h2>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Trong thời đại ng&agrave;y nay m&agrave; mọi người đều c&oacute; quyền truy cập v&agrave; sử dụng c&aacute;c c&ocirc;ng nghệ ti&ecirc;n tiến nhất từng được tạo ra,&nbsp;rất dễ bị đ&aacute;nh lừa bởi tin tặc v&agrave; kẻ trộm danh t&iacute;nh người d&ugrave;ng.&nbsp;Nếu kh&ocirc;ng thận trọng,&nbsp;bạn c&oacute; thể mất sạch to&agrave;n bộ cơ sở dữ liệu th&ocirc;ng tin quan trọng trong v&ograve;ng một đ&ecirc;m.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Giống như bạn kiểm tra tất cả những thiếu s&oacute;t trong quảng c&aacute;o của m&igrave;nh v&agrave; khoảng thời gian x&aacute;c định v&agrave; hiệu chỉnh nhu cầu của kh&aacute;ch h&agrave;ng nhiều lần,&nbsp;bạn cũng phải li&ecirc;n tục kiểm tra c&aacute;c lỗ hổng trong hệ thống bảo mật v&agrave; c&aacute;c khu vực tiềm ẩn rủi ro bị r&ograve; rỉ trong dữ liệu của bạn.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Để l&agrave;m được điều n&agrave;y,&nbsp;bạn cần đầu tư v&agrave;o c&aacute;c giải ph&aacute;p phần mềm bảo mật hiện đại c&oacute; thể gi&uacute;p bảo vệ dữ liệu của bạn khỏi tin tặc v&agrave; c&aacute;c nguồn lừa đảo độc hại kh&aacute;c.&nbsp;Thực tế l&agrave; bạn n&ecirc;n cố gắng hết sức để đảm bảo rằng c&aacute;c m&aacute;y chủ của bạn v&agrave; tất cả c&aacute;c hệ thống m&aacute;y t&iacute;nh m&agrave; nh&oacute;m dịch vụ kh&aacute;ch h&agrave;ng của bạn sử dụng đều an to&agrave;n v&agrave; ph&ugrave; hợp với tất cả c&aacute;c y&ecirc;u cầu tu&acirc;n thủ bảo mật.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Để bảo mật m&aacute;y chủ,&nbsp;bạn sẽ cần bảo vệ cả mạng cũng như hệ điều h&agrave;nh.&nbsp;Điều n&agrave;y cần phải được coi trọng v&agrave; đầu tư nguồn lực của c&ocirc;ng ty để ho&agrave;n th&agrave;nh.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Đối với hệ thống m&aacute;y t&iacute;nh,m&aacute;y tinh x&aacute;ch tay m&agrave; bạn cung cấp cho nh&acirc;n vi&ecirc;n,bạn phải đầu tư chương tr&igrave;nh phần mềm chống m&atilde; độc tốt để đảm bảo an to&agrave;n cho email,th&ocirc;ng tin mật v&agrave; c&aacute;c tập tin quan trọng.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><span style='font-family:"Times New Roman",serif;color:#2F5496;font-weight:bold;'><span style="font-size:21px;line-height:107%;">2.T</span></span><span style='font-family:"Times New Roman",serif;color:#2F5496;font-weight:bold;'><span style="font-size:21px;line-height:107%;">ạ</span></span><span style='font-family:"Times New Roman",serif;color:#2F5496;font-weight:bold;'><span style="font-size:21px;line-height:107%;">o mật khẩu phức tạp</span></span>:</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Một c&aacute;ch đơn giản v&agrave; hiệu quả để bảo vệ tất cả dữ liệu ( động v&agrave; tĩnh) l&agrave; tạo một mật khẩu đủ kh&oacute; để kh&ocirc;ng thể theo d&otilde;i.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Mật khẩu mạnh g&acirc;y kh&oacute; khăn cho tin tặc v&agrave; những người c&oacute; &yacute; đồ xấu x&acirc;m nhập v&agrave;o hệ thống của ch&uacute;ng t&ocirc;i v&agrave; l&agrave;m x&aacute;o trộn dữ liệu cũng như c&aacute;c tập tin quan trọng.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Do đ&oacute;,&nbsp;h&atilde;y c&acirc;n nhắc cung cấp cho tổ chức của bạn một hướng dẫn về quy tắc để tạo mật khẩu phức tạp hơn.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Một t&ugrave;y chọn kh&aacute;c l&agrave; sử dụng chương tr&igrave;nh quản l&yacute; mật khẩu.&nbsp;C&aacute;c ứng dụng n&agrave;y c&oacute; thể hỗ trợ bạn trong việc tạo mật khẩu kh&oacute; hơn,&nbsp;điều n&agrave;y sẽ l&agrave;m giảm khả năng bị tấn c&ocirc;ng trực tuyến của bạn trước c&aacute;c cuộc tấn c&ocirc;ng dựa tr&ecirc;n mật khẩu.&nbsp;Bạn c&oacute; thể đặt c&aacute;c tham số,&nbsp;chẳng hạn như độ d&agrave;i v&agrave; c&aacute;c k&iacute; tự đặc biệt,&nbsp;v&agrave; chương tr&igrave;nh sẽ tạo một mật khẩu mạnh v&agrave; an to&agrave;n.&nbsp;C&aacute;c ứng dụng n&agrave;y cũng lưu trữ mật khẩu v&agrave; loại bỏ sự kh&oacute; khăn khi phải ghi nhớ mật khẩu bao gồm c&aacute;c chuỗi chữ số,&nbsp;k&yacute; tự đặc biệt.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <h2 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:19px;font-family:"Times New Roman",serif;color:#2F5496;'>3.Hạn chế truy cập b&ecirc;n ngo&agrave;i với c&aacute;c mạng ri&ecirc;ng:</h2>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><span style="background:yellow;">Hầu hết c&aacute;c c&ocirc;ng ty c&oacute; rất nhiều dữ liệu lu&acirc;n chuyển tr&ecirc;n to&agrave;n cầu nhưng vẫn chưa c&oacute; c&aacute;ch chuẩn h&oacute;a n&agrave;o để đảm bảo an to&agrave;n tuyệt đối cho dữ liệu đ&oacute;.</span><span style="background:yellow;">&nbsp;</span><span style="background:yellow;">Nhưng tin tốt l&agrave; bạn vẫn c&oacute; thể đảm bảo rằng tin tặc chưa bắt được những lỗ hổng đ&oacute; ngay tức th&igrave;.</span></p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Ng&agrave;y nay,&nbsp;để giữ mọi thứ an to&agrave;n v&agrave; tập trung,&nbsp;việc sử dụng một VPN đ&aacute;ng tin cậy l&agrave; điều tuyệt đối bắt buộc.&nbsp;Tại sao?&nbsp;Bởi v&igrave; n&oacute; hoạt động như bức tường lửa cuối c&ugrave;ng để gi&uacute;p nh&oacute;m của bạn bảo vệ dữ liệu b&iacute; mật v&agrave; lu&ocirc;n giữ tất cả th&ocirc;ng tin quan trọng trong một v&ograve;ng lặp kh&oacute; c&oacute; thể ph&aacute; vỡ.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Dưới đ&acirc;y l&agrave; những g&igrave; VPN sẽ l&agrave;m cho nh&oacute;m của bạn:</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'><br>* Truy cập từ xa:&nbsp;điều n&agrave;y sẽ đảm bảo rằng nh&oacute;m nội bộ,&nbsp;từ xa hoặc trực tuyến của bạn lu&ocirc;n an to&agrave;n bằng c&aacute;ch l&agrave;m việc tr&ecirc;n c&ugrave;ng một mạng chung,&nbsp;gi&uacute;p bạn quản l&yacute; nh&oacute;m dễ d&agrave;ng hơn.&nbsp;Ngo&agrave;i ra n&oacute; sẽ giữ an to&agrave;n cho dữ liệu được chia sẻ v&agrave; đảm bảo rằng mọi c&aacute; nh&acirc;n đang hoạt động tr&ecirc;n c&ugrave;ng một mạng văn ph&ograve;ng cho d&ugrave; họ thiết lập kh&ocirc;ng gian l&agrave;m việc ở đ&acirc;u.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>* Kiểm so&aacute;t t&ugrave;y chỉnh:&nbsp;cơ sở kiểm so&aacute;t t&ugrave;y chỉnh gi&uacute;p bạn kiểm so&aacute;t quyền&nbsp;truy cập của mọi người v&agrave;o trang web,&nbsp;mật khẩu v&agrave; tất cả th&ocirc;ng tin động n&oacute;i chung.&nbsp;N&oacute; cho ph&eacute;p bạn duy tr&igrave; bảo mật ở một mức độ l&acirc;u hơn&nbsp;nơi bạn c&oacute; thể bảo vệ dữ liệu c&ocirc;ng ty của m&igrave;nh v&agrave; hệ thống m&aacute;y t&iacute;nh đang được sử dụng bởi lực lượng lao động của bạn tr&ecirc;n to&agrave;n thế giới.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:58.6pt;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:21px;font-family:"Times New Roman",serif;color:#2F5496;'>4.Giải th&iacute;ch ch&iacute;nh s&aacute;ch bảo mật của bạn một c&aacute;ch minh bạch:</h1>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Một bước đi kh&ocirc;n ngoan kh&aacute;c m&agrave; t&ocirc;i tin rằng mọi tổ chức phải ch&acirc;n th&agrave;nh thực hiện l&agrave; ch&uacute;ng ta trung thực với kh&aacute;ch h&agrave;ng của m&igrave;nh.&nbsp;C&aacute;c đối t&aacute;c kinh doanh phải lu&ocirc;n biết về c&aacute;ch dữ liệu của họ được truy cập,&nbsp;lưu trữ v&agrave; sử dụng như thế n&agrave;o.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Do đ&oacute;,&nbsp;bạn phải đưa ra một kế hoạch bảo đảm về an ninh mạng đảm bảo minh bạch ở cả hai ph&iacute;a.&nbsp;Việc cung cấp cho kh&aacute;ch h&agrave;ng quyền tự do quyết định xem họ c&oacute; muốn chia sẻ dữ liệu của m&igrave;nh hay kh&ocirc;ng cũng l&agrave; một việc t&ocirc;n trọng v&agrave; c&oacute; đạo đức.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>M&ocirc; h&igrave;nh &ldquo; Duy tr&igrave; sự minh bạch với kh&aacute;ch h&agrave;ng &ldquo; song h&agrave;nh với việc ph&aacute;t triển c&aacute;c phương ph&aacute;p thu thập v&agrave; bảo mật dữ liệu tốt hơn v&agrave; đ&aacute;ng tin cậy hơn.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>Dưới đ&acirc;y l&agrave; một số phương &aacute;n bổ sung nhỏ :</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:49.25pt;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>*Ch&iacute;nh s&aacute;ch quyền ri&ecirc;ng tư v&agrave; nội dung về an ninh mạng của c&ocirc;ng ty bạn n&ecirc;n được chia th&agrave;nh nhiều phần ngắn gọn,&nbsp;dễ hiểu v&agrave; được viết theo c&aacute;ch m&agrave; mọi người đều c&oacute; thể hiểu được.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:49.25pt;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>*Cung cấp cho kh&aacute;ch h&agrave;ng của bạn c&aacute;c bản cập nhật bảo mật thường xuy&ecirc;n.&nbsp;L&agrave;m được điều n&agrave;y,&nbsp;bạn sẽ tạo dựng được t&ecirc;n tuổi v&agrave; uy t&iacute;n hơn tr&ecirc;n thị trường v&agrave; giữ được sự t&iacute;n nhiệm của kh&aacute;ch h&agrave;ng.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:49.25pt;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:21px;font-family:"Times New Roman",serif;color:#2F5496;'>&nbsp; 5.M&atilde; h&oacute;a dữ liệu kh&aacute;ch h&agrave;ng :</h1>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Kh&ocirc;ng c&oacute; g&igrave; ngạc nhi&ecirc;n khi c&aacute;c tổ chức,&nbsp;bất kể quy m&ocirc; lớn hay nhỏ,&nbsp;sẽ kh&oacute; theo d&otilde;i v&agrave; kiểm so&aacute;t th&ocirc;ng tin nhạy cảm v&agrave; dữ liệu b&iacute; mật.&nbsp;Tr&ecirc;n thực tế theo một cuộc khảo s&aacute;t,&nbsp;người ta thấy được rằng:</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>*63 % người được hỏi hầu như kh&ocirc;ng thể theo d&otilde;i v&agrave; kiểm so&aacute;t dữ liệu được m&atilde; h&oacute;a v&igrave; c&ocirc;ng nghệ th&ocirc; sơ v&agrave; kh&ocirc;ng hiệu quả.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:36.0pt;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>*19 % n&oacute;i rằng họ kh&ocirc;ng cảm thấy cần phải m&atilde; h&oacute;a dữ liệu.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:36.0pt;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>*Chỉ 79 % b&aacute;o c&aacute;o cho rằng họ c&oacute; bất kỳ loại c&ocirc;ng cụ n&agrave;o để hỗ trợ an ninh mạng.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Do đ&oacute; ch&uacute;ng t&ocirc;i cần nhiều hệ thống v&agrave; c&ocirc;ng nghệ tối ưu hơn để đảm bảo an to&agrave;n v&agrave; bảo mật m&agrave; dữ liệu của ch&uacute;ng t&ocirc;i cần ng&agrave;y nay.&nbsp;Bằng c&aacute;ch triển khai m&atilde; h&oacute;a dữ liệu,&nbsp;ch&uacute;ng t&ocirc;i c&oacute; thể ho&agrave;n th&agrave;nh mục ti&ecirc;u n&agrave;y một c&aacute;ch th&agrave;nh c&ocirc;ng.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Qu&aacute; tr&igrave;nh m&atilde; h&oacute;a gi&uacute;p bạn m&atilde; h&oacute;a tất cả dữ liệu được giao tiếp để kh&ocirc;ng rơi v&agrave;o tay người d&ugrave;ng tr&aacute;i ph&eacute;p.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>M&atilde; h&oacute;a dữ liệu như DES,&nbsp;AES,&nbsp;3DES,&nbsp;Twofish &hellip; l&agrave; những v&iacute; dụ về c&aacute;c phương ph&aacute;p ti&ecirc;u chuẩn m&agrave; c&aacute;c c&ocirc;ng ty tu&acirc;n theo để đảm bảo an to&agrave;n cho th&ocirc;ng tin v&agrave; dữ liệu của kh&aacute;ch h&agrave;ng của họ.</p>
          <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:21px;font-family:"Times New Roman",serif;color:#2F5496;'>6.Kiểm tra c&aacute;c lỗi bảo mật:</h1>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Một số tổ chức đầu tư rất nhiều c&ocirc;ng sức v&agrave; tiền&nbsp;của v&agrave;o việc l&agrave;m cho c&aacute;c nền tảng v&agrave; dịch vụ của họ trở n&ecirc;n an to&agrave;n v&agrave; bảo mật hơn.&nbsp;Tuy nhi&ecirc;n,&nbsp;khi thời gian tr&ocirc;i qua,&nbsp;những c&ocirc;ng nghệ đ&oacute; trở n&ecirc;n lỗi thời v&agrave; cần phải c&oacute; một giải ph&aacute;p hiệu quả hơn để bắt kịp tốc độ v&agrave; giải quyết vấn đề phức tạp n&agrave;y</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>V&iacute; dụ,&nbsp;Yahoo đ&atilde; c&oacute; một vụ vi phạm lớn v&agrave;o năm 2013 khi tin tặc đ&aacute;nh cắp th&ocirc;ng tin nhạy cảm của một số lượng kh&aacute; lớn người d&ugrave;ng.&nbsp;Một trường hợp kh&aacute;c l&agrave; khi một vụ vi phạm dữ liệu xảy ra tại Văn ph&ograve;ng Quản l&yacute; nh&acirc;n sự,&nbsp;nơi dữ liệu c&aacute; nh&acirc;n v&agrave; số nhận dạng sinh trắc học của hơn 20 triệu người đ&atilde; bị c&ocirc;ng khai v&agrave;o năm 2015</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Dữ liệu cho thấy,&nbsp;với việc gia tăng khả năng tiếp cận với c&aacute;c c&ocirc;ng nghệ ti&ecirc;n tiến,&nbsp;ng&agrave;y c&agrave;ng c&oacute; nhu cầu về c&aacute;c biện ph&aacute;p bảo mật được cải thiện khi c&aacute;c y&ecirc;u cầu v&agrave; kỳ vọng của c&ocirc;ng ch&uacute;ng dần thay đổi theo thời gian.</p>
          <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:21px;font-family:"Times New Roman",serif;color:#2F5496;'>7.Lưu trữ dữ liệu dịch vụ kh&aacute;ch h&agrave;ng trong phần mềm trợ gi&uacute;p:</h1>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Một điều kh&aacute;c bạn c&oacute; thể l&agrave;m l&agrave; tập trung,&nbsp;sắp xếp v&agrave; lưu trữ dữ liệu dịch vụ kh&aacute;ch h&agrave;ng một c&aacute;ch an to&agrave;n trong một c&ocirc;ng cụ hỗ trợ dịch vụ.&nbsp;Thực hiện kĩ thuật n&agrave;y v&agrave; &aacute;p dụng nền tảng phần mềm trợ gi&uacute;p tốt cho dịch vụ kh&aacute;ch h&agrave;ng sẽ gi&uacute;p bạn đảm bảo rằng tất cả dữ liệu kh&aacute;ch h&agrave;ng được an to&agrave;n v&agrave; được bảo vệ trong c&aacute;c khu chứa.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>V&igrave; ch&uacute;ng ta đang sống trong một thế giới m&agrave; loại c&ocirc;ng nghệ n&agrave;y tồn tại,&nbsp;n&ecirc;n sẽ kh&ocirc;ng th&ocirc;ng minh nếu như kh&ocirc;ng đầu tư v&agrave;o loại c&ocirc;ng nghệ n&agrave;y.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Phần mềm trợ gi&uacute;p n&agrave;y sẽ gi&uacute;p bạn giữ cho dữ liệu được ngăn nắp v&agrave; an to&agrave;n,&nbsp;đồng thời cho ph&eacute;p nh&oacute;m hỗ trợ của bạn phản hồi kh&aacute;ch h&agrave;ng tốt hơn.&nbsp;N&oacute; cho ph&eacute;p bạn theo d&otilde;i c&aacute;c truy vấn,&nbsp;chỉ định c&aacute;c ticket cần giải quyết cho c&aacute;c nh&acirc;n vi&ecirc;n trợ gi&uacute;p v&agrave; cung cấp hỗ trợ cho mọi kh&aacute;ch h&agrave;ng.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Hệ thống cũng sẽ loại bỏ nhu cầu dữ liệu được m&atilde; h&oacute;a tr&ecirc;n đĩa v&agrave; cho ph&eacute;p bạn truy cập th&ocirc;ng tin ở bất kỳ đ&acirc;u v&agrave; bất kỳ l&uacute;c n&agrave;o v&igrave; đ&acirc;y l&agrave; phần mềm dựa tr&ecirc;n thuật to&aacute;n đ&aacute;m m&acirc;y.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:54.0pt;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:21px;font-family:"Times New Roman",serif;color:#2F5496;'>8.Lu&ocirc;n cập nhật v&agrave; tu&acirc;n thủ c&aacute;c quy định thay đổi :</h1>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>C&aacute;ch tốt nhất để giữ li&ecirc;n quan đến kh&iacute;a cạnh bảo mật của c&aacute;c dịch vụ v&agrave; sản phẩm m&agrave; bạn cung cấp l&agrave; tu&acirc;n thủ c&aacute;c nguy&ecirc;n tắc v&agrave; ti&ecirc;u chuẩn bảo mật hiện h&agrave;nh.V&iacute; dụ :Luật An To&agrave;n th&ocirc;ng tin mạng ( 2015) của Việt Nam n&ecirc;u r&otilde; quyền,&nbsp;tr&aacute;ch nhiệm của c&aacute;c b&ecirc;n trong việc đảm bảo an to&agrave;n th&ocirc;ng tin mạng,&nbsp;mật m&atilde; d&acirc;n sự,&nbsp;ti&ecirc;u chuẩn,&nbsp;quy chuẩn kỹ thuật về an to&agrave;n th&ocirc;ng tin mạng&hellip;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Ch&uacute; &yacute; đến việc tu&acirc;n thủ quy định sẽ gi&uacute;p bạn đồng thời tu&acirc;n thủ luật ph&aacute;p v&agrave; ti&ecirc;u chuẩn h&oacute;a hoạt động kinh doanh của m&igrave;nh.&nbsp;Do đ&oacute;,&nbsp;h&atilde;y tu&acirc;n thủ ch&iacute;nh s&aacute;ch bảo mật của bạn,&nbsp;lu&ocirc;n kiểm tra c&aacute;c phương ph&aacute;p đảm bảo an to&agrave;n v&agrave; mọi thứ bạn đang l&agrave;m đều tu&acirc;n thủ c&aacute;c bản cập nhật bảo mật mới nhất.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:54.0pt;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:21px;font-family:"Times New Roman",serif;color:#2F5496;'>9.Chuẩn bị sẵn kế hoạch xử l&yacute; khủng hoảng :</h1>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Quản l&yacute; dự &aacute;n,&nbsp;quản l&yacute; con người,&nbsp;quản l&yacute; nh&oacute;m v&agrave; kế hoạch quản l&yacute; sản phẩm l&agrave; chưa ho&agrave;n thiện nếu kh&ocirc;ng c&oacute; chiến lược quản l&yacute; rủi ro.&nbsp;Kế hoạch thứ hai,&nbsp;hoặc tốt hơn l&agrave; phương &aacute;n an to&agrave;n dự ph&ograve;ng,&nbsp;l&agrave; cần thiết nếu bạn đang mạo hiểm với một lượng lớn dữ liệu kh&aacute;ch h&agrave;ng.&nbsp;Phải c&oacute; tường lửa sau tường lửa để bạn c&oacute; thể bảo mật th&ocirc;ng tin nhạy cảm n&agrave;y.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Ngo&agrave;i ra,&nbsp;nếu bạn chuẩn bị đối ph&oacute; với một vi phạm bảo mật một c&aacute;ch hiệu quả,&nbsp;bạn c&oacute; thể giảm đ&aacute;ng kể t&aacute;c động của n&oacute; đối với doanh nghiệp của bạn.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>H&atilde;y xem một số bước bạn c&oacute; thể thực hiện để chuẩn bị v&agrave; đối ph&oacute; với t&igrave;nh huống xấu nhất:</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:49.25pt;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>*Tạo ra một t&agrave;i liệu cụ thể cho chiến lược quản l&yacute; khủng hoảng;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:49.25pt;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>*X&acirc;y dựng đội quản l&yacute; khủng hoảng;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:49.25pt;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>*Đ&aacute;nh gi&aacute; xem nh&oacute;m của bạn xử l&yacute; t&igrave;nh huống quan trọng như thế n&agrave;o;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:49.25pt;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>*Cung cấp cho nh&acirc;n vi&ecirc;n của bạn chương tr&igrave;nh đ&agrave;o tạo để đối ph&oacute; với khủng hoảng như thế n&agrave;o !</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>H&atilde;y nhớ rằng vi phạm dữ liệu c&oacute; thể xảy ra trong nh&aacute;y mắt hoặc thỉnh thoảng diễn ra.&nbsp;V&igrave; vậy điều cần thiết l&agrave; bạn phải chuẩn bị trước cho điều tồi tệ nhất.</p>
          <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:21px;font-family:"Times New Roman",serif;color:#2F5496;'>Kết luận:</h1>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Bảo vệ dữ liệu của kh&aacute;ch h&agrave;ng l&agrave; rất quan trọng v&igrave; một l&yacute; do ch&iacute;nh:&nbsp;sự th&agrave;nh c&ocirc;ng của doanh nghiệp phụ thuộc v&agrave;o n&oacute;.&nbsp;Việc thiếu c&aacute;c biện ph&aacute;p ph&ograve;ng ngừa đảm bảo bảo vệ dữ liệu cho kh&aacute;ch h&agrave;ng sẽ khiến bạn bị tấn c&ocirc;ng,&nbsp;dẫn đến mất l&ograve;ng tin của kh&aacute;ch h&agrave;ng,&nbsp;ti&ecirc;u hao tiền&nbsp;của,&nbsp;bị phạt,&nbsp;bị kiện tụng&hellip;.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Để giữ cho dữ liệu của kh&aacute;ch h&agrave;ng an to&agrave;n v&agrave; năng động,&nbsp;c&aacute;c c&ocirc;ng ty phải c&oacute; một kế hoạch bảo mật dữ liệu vững chắc m&agrave; họ li&ecirc;n tục kiểm tra v&agrave; điều chỉnh.</p>
          <p style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;text-align:justify;'>Nếu bạn chưa bao giờ kiểm tra c&aacute;c biện ph&aacute;p bảo vệ dữ liệu c&ocirc;ng ty v&agrave; kh&aacute;ch h&agrave;ng của m&igrave;nh trước đ&acirc;y hoặc đ&atilde; kh&ocirc;ng l&agrave;m như vậy trong một thời gian d&agrave;i,&nbsp;th&igrave; 9 phương ph&aacute;p kể tr&ecirc;n sẽ gi&uacute;p bạn bắt đầu với n&oacute; ngay lập tức.</p>`,
        },
      ],
    };
  },
  methods: {
    async fetchData() {
      let vm = this;
      // this.collapses[1].text = data;
      let data = await vm.$store.dispatch("fetchData",load_api.setting.setting);
      //Fetch điều khoản dịch vụ
      this.collapses[0].text = data.data.terms_of_use;
    },
  },
  mounted() {
    var vm = this;
    vm.$nextTick(async () => {
      await vm.fetchData();
    });
  },

}
</script>
