<template>
  <div>
    <blockquote class="blockquote text-center bg-white">
      <h1 class="mb-0">Chính sách</h1>
    </blockquote>
    <div class="container">
      <div class="bg-white p-2  rounded-3">
        <div class="row">
          <div class="col-md-12">
            
          <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;text-align:center;line-height:107%;font-size:21px;font-family:"Times New Roman",serif;color:#203864;font-weight:bold;'>Privacy Policy</h1>
          <h2 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;text-align:center;line-height:107%;font-size:19px;font-family:"Times New Roman",serif;color:#2F5496;font-weight:normal;'>C&Aacute;CH e-GATE XỬ L&Yacute; DỮ LIỆU CỦA BẠN</h2>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'>&nbsp;</p>
          <h3 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;color:#1F3763;font-weight:bold;'>Giới thiệu:</h3>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;text-align:justify;'>Với sứ mệnh l&agrave;m cho việc thương mại tốt hơn cho tất cả mọi người tại e-GATE,&nbsp;ch&uacute;ng t&ocirc;i sẽ thu thập v&agrave; sử dụng th&ocirc;ng tin về bạn:</p>
          <ul style="list-style-type: undefined;">
              <li>C&aacute;c shippers sử dụng e-Gate để hỗ trợ tối ưu c&ocirc;ng việc.</li>
              <li>Người&nbsp;d&ugrave;ng e-Gate mua sắm tại c&aacute;c s&agrave;n thương mại điện tử do e-Gate hỗ trợ.</li>
              <li>C&aacute;c đối t&aacute;c ph&aacute;t triển ứng dụng cho Người ti&ecirc;u d&ugrave;ng online.</li>
              <li>Kh&aacute;ch truy cập v&agrave;o c&aacute;c trang web của e-Gate hoặc bất k&igrave; ai li&ecirc;n hệ với bộ phận hỗ trợ của e-Gate.</li>
          </ul>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;text-align:justify;'>Ch&iacute;nh s&aacute;ch bảo mật n&agrave;y sẽ gi&uacute;p bạn hiểu r&otilde; hơn về c&aacute;ch ch&uacute;ng t&ocirc;i thu thập,&nbsp;sử dụng v&agrave; chia sẻ th&ocirc;ng tin c&aacute; nh&acirc;n của bạn.&nbsp;Nếu ch&uacute;ng t&ocirc;i thay đổi c&aacute;c thực tiễn về quyền ri&ecirc;ng tư của m&igrave;nh,&nbsp;nội dung mới sẽ được cập nhật ngay lập tức v&agrave; th&ocirc;ng b&aacute;o cho bạn (th&ocirc;ng qua admin của e-Gate hoặc qua email)</p>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'>&nbsp;</p>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'><span style='font-family:"Times New Roman",serif;color:#1F3763;font-weight:bold;'>Gi&aacute; trị của ch&uacute;ng t&ocirc;i</span>:</p>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;text-align:justify;'>Niềm tin l&agrave; nền tảng của e-Gate bao gồm việc tin tưởng ch&uacute;ng t&ocirc;i sẽ sử dụng th&ocirc;ng tin của bạn v&agrave;o những điều đ&uacute;ng đắn.&nbsp;Ba gi&aacute; trị ch&iacute;nh dẫn dắt ch&uacute;ng t&ocirc;i khi trải qua qu&aacute; tr&igrave;nh ph&aacute;t triển c&aacute;c sản phẩm v&agrave; dịch vụ của m&igrave;nh.&nbsp;Những gi&aacute; trị n&agrave;y sẽ gi&uacute;p bạn hiểu r&otilde; hơn c&aacute;ch ch&uacute;ng t&ocirc;i nghĩ về th&ocirc;ng tin v&agrave; quyền ri&ecirc;ng tư của bạn:</p>
          <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>
              <ul style="margin-bottom:0cm;list-style-type: undefined;">
                  <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><strong>Th&ocirc;ng tin của bạn thuộc về ch&iacute;nh bạn</strong> :</li>
              </ul>
          </div>
          <p style='margin-right:0cm;margin-left:18.0pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;text-align:justify;'>Ch&uacute;ng t&ocirc;i sẽ ph&acirc;n t&iacute;ch cẩn thận những loại th&ocirc;ng tin n&agrave;o ch&uacute;ng t&ocirc;i cần để cung cấp dịch vụ của m&igrave;nh v&agrave; sẽ cố gắng giới hạn những loại th&ocirc;ng tin ch&uacute;ng t&ocirc;i thu thập l&agrave; thực sự cần thiết.&nbsp;Nếu cần thiết,&nbsp;ch&uacute;ng t&ocirc;i sẽ x&oacute;a hoặc ẩn danh th&ocirc;ng tin n&agrave;y khi kh&ocirc;ng c&ograve;n cần thiết nữa.&nbsp;Khi x&acirc;y dựng v&agrave; cải tiến sản phẩm n&agrave;y,&nbsp;c&aacute;c kĩ sư của ch&uacute;ng t&ocirc;i đ&atilde; l&agrave;m việc chặt chẽ với c&aacute;c nh&oacute;m bảo mật quyền ri&ecirc;ng tư của ch&uacute;ng t&ocirc;i để x&acirc;y dựng chặt chẽ lộ tr&igrave;nh cho việc đảm bảo an to&agrave;n th&ocirc;ng tin.&nbsp;Nguy&ecirc;n tắc quan trọng nhất của ch&uacute;ng t&ocirc;i l&agrave; th&ocirc;ng tin của bạn thuộc về ch&iacute;nh bạn v&agrave; ch&uacute;ng t&ocirc;i sẽ chỉ sử dụng c&aacute;c th&ocirc;ng tin đ&oacute; cho lợi &iacute;ch của bạn.</p>
          <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>
              <ul style="margin-bottom:0cm;list-style-type: undefined;">
                  <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><strong>Ch&uacute;ng t&ocirc;i bảo vệ th&ocirc;ng tin của bạn khỏi những b&ecirc;n kh&ocirc;ng li&ecirc;n quan kh&aacute;c</strong>:</li>
              </ul>
          </div>
          <p style='margin-right:0cm;margin-left:18.0pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:.0001pt;line-height:107%;text-align:justify;'>Nếu b&ecirc;n thứ ba y&ecirc;u cầu cung cấp th&ocirc;ng tin c&aacute; nh&acirc;n của bạn,&nbsp;ch&uacute;ng t&ocirc;i sẽ từ chối chia sẻ đ&oacute; trừ khi bạn cho ph&eacute;p hoặc ch&uacute;ng t&ocirc;i được y&ecirc;u cầu về mặt ph&aacute;p l&yacute;.&nbsp;Khi ch&uacute;ng t&ocirc;i được y&ecirc;u cầu chia sẻ th&ocirc;ng tin c&aacute; nh&acirc;n của bạn qua con đường hợp ph&aacute;p,&nbsp;ch&uacute;ng t&ocirc;i sẽ cho bạn biết trước,&nbsp;trừ khi điều đ&oacute; kh&ocirc;ng được luật ph&aacute;p cho ph&eacute;p.</p>
          <p style='margin-right:0cm;margin-left:18.0pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:.0001pt;line-height:107%;'>&nbsp;</p>
          <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>
              <ul style="margin-bottom:0cm;list-style-type: undefined;">
                  <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'><strong>Ch&uacute;ng t&ocirc;i sẽ y&ecirc;u cầu nh&agrave; cung cấp v&agrave; c&aacute;c đối t&aacute;c đ&aacute;p ứng nghĩa vụ về quyền ri</strong><strong>&ecirc;ng tư của họ</strong>:</li>
              </ul>
          </div>
          <p style='margin-right:0cm;margin-left:18.0pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;text-align:justify;'>Nhiều nh&agrave; cung cấp v&agrave; đối t&aacute;c sử dụng e-Gate kh&ocirc;ng r&otilde; r&agrave;ng trong việc x&acirc;y dựng c&aacute;c quy tắc về quyền ri&ecirc;ng tư,&nbsp;v&igrave; vậy e-Gate c&oacute; nghĩa vụ v&agrave; tr&aacute;ch nhiệm nhắc nhở c&aacute;c b&ecirc;n li&ecirc;n quan về việc đ&aacute;p ứng c&aacute;c nghĩa vụ về quyền ri&ecirc;ng tư.&nbsp;Để l&agrave;m được điều n&agrave;y,&nbsp;ch&uacute;ng t&ocirc;i sẽ cố gắng x&acirc;y dựng c&aacute;c sản phẩm v&agrave; dịch vụ của m&igrave;nh để c&oacute; thể dễ d&agrave;ng sử dụng th&acirc;n thiện với c&aacute;c y&ecirc;u cầu về quyền ri&ecirc;ng tư nhất.&nbsp;Ch&uacute;ng t&ocirc;i sẽ cung cấp c&aacute;c C&acirc;u hỏi thường gặp chi tiết nhất,&nbsp;t&agrave;i liệu m&ocirc; tả những ch&iacute;nh s&aacute;ch quan trọng nhất v&agrave; trả lời những c&acirc;u hỏi li&ecirc;n quan.</p>
          <p style='margin-right:0cm;margin-left:18.0pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'>&nbsp;</p>
          <h3 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;color:#1F3763;font-weight:bold;'>Tại sao ch&uacute;ng t&ocirc;i xử l&yacute; th&ocirc;ng tin của bạn :</h3>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;text-align:justify;'>Ch&uacute;ng t&ocirc;i thường xử l&yacute; th&ocirc;ng tin của bạn v&igrave; n&oacute; l&agrave; cần thiết trong qu&aacute; tr&igrave;nh ho&agrave;n th&agrave;nh nghĩa vụ theo hợp đồng (v&iacute; dụ : xử l&yacute; c&aacute;c khoản thanh to&aacute;n đăng k&iacute; của bạn để sử dụng nền tảng của e- Gate) hoặc khi ch&uacute;ng t&ocirc;i hoặc đối t&aacute;c cần sử dụng th&ocirc;ng tin c&aacute; nh&acirc;n của bạn v&igrave; một l&iacute; do li&ecirc;n quan do doanh nghiệp của họ ( v&iacute; dụ: để cung cấp cho bạn một dịch vụ kh&aacute;c).&nbsp;Luật ph&aacute;p gọi những l&iacute; do đ&oacute; l&agrave; &ldquo; lợi &iacute;ch hợp ph&aacute;p&rdquo;.&nbsp;Những lợi &iacute;ch hợp ph&aacute;p n&agrave;y sẽ bao gồm:</p>
          <ul style="list-style-type: undefined;">
              <li>Ngăn ngừa rủi ro v&agrave; gian lận;</li>
              <li>Trả lời c&aacute;c c&acirc;u hỏi hoặc cung cấp c&aacute;c loại hỗ trợ kh&aacute;c;</li>
              <li>Gi&uacute;p c&aacute;c đối t&aacute;c t&igrave;m v&agrave; sử dụng ứng dụng th&ocirc;ng qua cửa h&agrave;ng ứng dụng của ch&uacute;ng t&ocirc;i;</li>
              <li>Cung cấp v&agrave; cải tiến c&aacute;c sản phẩm v&agrave; dịch vụ của ch&uacute;ng t&ocirc;i;</li>
              <li>Cung cấp c&aacute;c b&aacute;o c&aacute;o v&agrave; ph&acirc;n t&iacute;ch về dữ liệu;</li>
              <li>Thử nghiệm c&aacute;c t&iacute;nh năng hoặc dịch vụ bổ sung hỗ trợ tiếp thị,&nbsp;quảng c&aacute;o hoặc truyền th&ocirc;ng.</li>
          </ul>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;text-align:justify;'>Bằng việc cung cấp sự minh bạch r&otilde; r&agrave;ng cho c&aacute;c thực tiễn về quyền ri&ecirc;ng tư của e-Gate,&nbsp;bạn sẽ dễ d&agrave;ng trong việc kiểm so&aacute;t th&ocirc;ng tin c&aacute; nh&acirc;n của m&igrave;nh khi th&iacute;ch hợp,&nbsp;hạn chế th&ocirc;ng tin ch&uacute;ng t&ocirc;i lưu trữ,&nbsp;hạn chế những g&igrave; ch&uacute;ng t&ocirc;i xử l&yacute; với th&ocirc;ng tin của bạn như:&nbsp;ch&uacute;ng t&ocirc;i sẽ gửi th&ocirc;ng tin cho ai,&nbsp;ch&uacute;ng t&ocirc;i lưu trữ th&ocirc;ng tin của bạn trong bao l&acirc;u hoặc c&aacute;c biện ph&aacute;p bảo vệ kĩ thuật m&agrave; ch&uacute;ng t&ocirc;i sử dụng để bảo vệ th&ocirc;ng tin của bạn.</p>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;text-align:justify;'>Một trong những c&aacute;ch ch&uacute;ng t&ocirc;i c&oacute; thể gi&uacute;p người d&ugrave;ng e-Gate l&agrave; sử dụng c&aacute;c kĩ thuật như &ldquo; AI Marchine Learning&rdquo; ( luật ph&aacute;p gọi đ&acirc;y l&agrave; &ldquo; ra quyết định tự động &ldquo;) để gi&uacute;p ch&uacute;ng t&ocirc;i cải thiện dịch vụ của m&igrave;nh.&nbsp;Khi ch&uacute;ng ta sử dụng AI marchine learning,th&igrave;:(1) vẫn c&oacute; con người tham gia v&agrave;o qu&aacute; tr&igrave;nh (v&agrave; do đ&oacute; qu&aacute; tr&igrave;nh n&agrave;y kh&ocirc;ng ho&agrave;n to&agrave;n tự động),&nbsp;hoặc (2) sử dụng AI theo những c&aacute;ch kh&ocirc;ng c&oacute; t&aacute;c động đ&aacute;ng kể đến quyền ri&ecirc;ng tư (v&iacute; dụ: sắp xếp lại c&aacute;ch ứng dụng c&oacute; thể xuất hiện khi bạn truy cập v&agrave;o cửa h&agrave;ng ứng dụng)</p>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'><span style='font-family:"Times New Roman",serif;color:#1F3763;font-weight:bold;'>Quyền của bạn đối với th&ocirc;ng tin của ch&iacute;nh bạn</span> :</p>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;text-align:justify;'>Ch&uacute;ng t&ocirc;i tin rằng bạn c&oacute; thể truy cập v&agrave; kiểm so&aacute;t th&ocirc;ng tin c&aacute; nh&acirc;n của m&igrave;nh cho d&ugrave; bạn sống ở đ&acirc;u.&nbsp;T&ugrave;y thuộc v&agrave;o c&aacute;ch bạn sử dụng e-Gate,&nbsp;bạn c&oacute; thể c&oacute; quyền y&ecirc;u cầu truy cập,&nbsp;sửa đổi,&nbsp;x&oacute;a,&nbsp;chuyển sang nh&agrave; cung cấp dịch vụ kh&aacute;c,&nbsp;hạn chế hoặc phản đối một số c&aacute;ch sử dụng th&ocirc;ng tin c&aacute; nh&acirc;n của bạn (v&iacute; dụ:tiếp thị trực tiếp).&nbsp;Ch&uacute;ng t&ocirc;i sẽ kh&ocirc;ng t&iacute;nh th&ecirc;m ph&iacute; hoặc cung cấp cho bạn một loại h&igrave;nh dịch vụ kh&aacute;c nếu bạn thực hiện bất k&igrave; quyền n&agrave;o trong số n&agrave;y.</p>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;text-align:justify;'>Nếu bạn thanh to&aacute;n cho một dịch vụ của đối t&aacute;c tr&ecirc;n nền tảng của e-Gate cung cấp v&agrave; muốn thực hiện c&aacute;c quyền n&agrave;y đối với th&ocirc;ng tin về giao dịch của m&igrave;nh,&nbsp;bạn cần li&ecirc;n hệ trực tiếp với b&ecirc;n thứ ba m&agrave; bạn đ&atilde; tương t&aacute;c.&nbsp;Ch&uacute;ng t&ocirc;i chỉ l&agrave; người xử l&yacute; thay mặt họ v&agrave; kh&ocirc;ng thể quyết định c&aacute;ch xử l&yacute; th&ocirc;ng tin của họ.&nbsp;Tất nhi&ecirc;n,&nbsp;ch&uacute;ng t&ocirc;i sẽ gi&uacute;p những đối t&aacute;c của m&igrave;nh thực hiện những y&ecirc;u cầu n&agrave;y bằng c&aacute;ch cung cấp cho họ c&ocirc;ng cụ để thực hiện tr&ecirc;n nền tảng e-Gate.</p>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;text-align:justify;'>Nếu bạn l&agrave; đối t&aacute;c,&nbsp;nh&agrave; cung cấp,&nbsp;nh&acirc;n vi&ecirc;n e-Gate hoặc c&aacute;c c&aacute; nh&acirc;n kh&aacute;c c&oacute; quan hệ trực tiếp tới e-Gate,&nbsp;vui l&ograve;ng gửi y&ecirc;u cầu về chủ đề dữ liệu của bạn th&ocirc;ng qua cổng th&ocirc;ng tin trực tuyến của ch&uacute;ng t&ocirc;i.&nbsp;Xin lưu &yacute; rằng nếu bạn gửi cho ch&uacute;ng t&ocirc;i một y&ecirc;u cầu li&ecirc;n quan đến th&ocirc;ng tin c&aacute; nh&acirc;n của bạn,&nbsp;ch&uacute;ng t&ocirc;i phải đảm bảo rằng đ&oacute; l&agrave; bạn trước khi ch&uacute;ng t&ocirc;i c&oacute; thể trả lời.&nbsp;Để l&agrave;m như vậy,&nbsp;ch&uacute;ng t&ocirc;i c&oacute; thể sử dụng b&ecirc;n thứ ba để thu thập v&agrave; x&aacute;c minh t&agrave;i liệu nhận dạng.</p>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;text-align:justify;'>Nếu bạn kh&ocirc;ng h&agrave;i l&ograve;ng với phản hồi của ch&uacute;ng t&ocirc;i cho một y&ecirc;u cầu cụ thể,&nbsp;bạn c&oacute; thể li&ecirc;n hệ với ch&uacute;ng t&ocirc;i trực tiếp để giải quyết vấn đề.&nbsp;Bạn cũng c&oacute; quyền li&ecirc;n hệ với cơ quan bảo vệ dữ liệu hoặc quyền ri&ecirc;ng tư tại địa phương của m&igrave;nh bất k&igrave; l&uacute;c n&agrave;o.</p>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'>&nbsp;</p>
          <h3 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;color:#1F3763;font-weight:bold;'>Nơi ch&uacute;ng t&ocirc;i gửi th&ocirc;ng tin cho bạn :</h3>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'>&nbsp;</p>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;text-align:justify;'>Ch&uacute;ng t&ocirc;i l&agrave; một c&ocirc;ng ty đến từ Việt Nam,&nbsp;nhưng ch&uacute;ng t&ocirc;i l&agrave;m việc v&agrave; xử l&yacute; dữ liệu về c&aacute;c c&aacute; nh&acirc;n tr&ecirc;n to&agrave;n thế giới.&nbsp;Để vận h&agrave;nh doanh nghiệp của ch&uacute;ng t&ocirc;i,c&oacute; thể ch&uacute;ng t&ocirc;i sẽ gửi th&ocirc;ng tin c&aacute; nh&acirc;n của bạn qua c&aacute;c tổ chức kh&aacute;c b&ecirc;n ngo&agrave;i địa phương của bạn cư tr&uacute;.&nbsp;Dữ liệu được gửi đi c&oacute; thể tu&acirc;n theo luật của quốc gia nơi ch&uacute;ng t&ocirc;i gửi dữ liệu tới.&nbsp;Khi thực hiện c&ocirc;ng việc n&agrave;y,&nbsp;ch&uacute;ng t&ocirc;i sẽ thực hiện c&aacute;c biện ph&aacute;p bảo vệ th&ocirc;ng tin của bạn v&agrave; sẽ cố gắng chỉ gửi th&ocirc;ng tin của bạn đến c&aacute;c qu&ocirc;c gia c&oacute; Luật bảo vệ dữ liệu mạnh mẽ nhất.</p>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;text-align:justify;'>T&oacute;m lại,&nbsp;trong khi ch&uacute;ng t&ocirc;i l&agrave;m những g&igrave; c&oacute; thể để bảo vệ th&ocirc;ng tin của bạn,&nbsp;đ&ocirc;i khi ch&uacute;ng t&ocirc;i c&oacute; thể bị y&ecirc;u cầu tiết lộ th&ocirc;ng tin c&aacute; nh&acirc;n của bạn&nbsp;(v&iacute; dụ :nếu ch&uacute;ng t&ocirc;i nhận được lệnh hầu t&ograve;a hợp lệ.)&nbsp;Để biết th&ocirc;ng tin về c&aacute;ch ch&uacute;ng t&ocirc;i phản hồi đối với c&aacute;c y&ecirc;u cầu như vậy,&nbsp;vui l&ograve;ng tham khảo <strong>Nguy&ecirc;n tắc của ch&uacute;ng t&ocirc;i về Y&ecirc;u cầu ph&aacute;p l&yacute;</strong>.</p>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'><span style='font-family:"Times New Roman",serif;color:#1F3763;font-weight:bold;'>C&aacute;ch ch&uacute;ng t&ocirc;i bảo vệ th&ocirc;ng tin của bạn</span>:</p>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;text-align:justify;'>Đội ngũ kĩ sư của ch&uacute;ng t&ocirc;i l&agrave;m việc kh&ocirc;ng mệt mỏi để bảo vệ th&ocirc;ng tin của bạn v&agrave; đảm bảo t&iacute;nh bảo mật cũng như to&agrave;n vẹn của nền tảng e-Gate.&nbsp;Ch&uacute;ng t&ocirc;i sử dụng c&aacute;c kiểm to&aacute;n vi&ecirc;n độc lập để đ&aacute;nh gi&aacute; t&iacute;nh bảo mật của việc lưu trữ dữ liệu v&agrave; hệ thống xử l&yacute; th&ocirc;ng tin t&agrave;i ch&iacute;nh của ch&uacute;ng t&ocirc;i.&nbsp;Tuy nhi&ecirc;n,&nbsp;ch&uacute;ng ta đều biết rằng kh&ocirc;ng c&oacute; phương thức truyền tải n&agrave;o qua Internet v&agrave; lưu trữ điện tử c&oacute; thể đảm bảo t&iacute;nh an to&agrave;n l&ecirc;n tới 100%.&nbsp;Điều n&agrave;y c&oacute; nghĩa l&agrave; ch&uacute;ng t&ocirc;i kh&ocirc;ng thể đảm bảo an to&agrave;n tuyệt đối cho th&ocirc;ng tin c&aacute; nh&acirc;n của bạn.&nbsp;Bạn c&oacute; thể t&igrave;m hiểu th&ecirc;m th&ocirc;ng tin về c&aacute;c biện ph&aacute;p bảo mật của ch&uacute;ng t&ocirc;i bằng c&aacute;ch tham khảo <strong>biện ph&aacute;p về bảo mật</strong> của e-Gate.</p>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'>&nbsp;</p>
          <h3 style='margin-top:2.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;color:#1F3763;font-weight:bold;'>C&aacute;ch ch&uacute;ng t&ocirc;i sử dụng &ldquo;Cookie&rdquo; v&agrave; c&aacute;c c&ocirc;ng nghệ theo d&otilde;i kh&aacute;c:</h3>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'>&nbsp;</p>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;text-align:justify;'>Ch&uacute;ng t&ocirc;i sẽ sử dụng Cookie v&agrave; c&aacute;c c&ocirc;ng nghệ theo d&otilde;i tương tự tr&ecirc;n trang Web của ch&uacute;ng t&ocirc;i v&agrave; khi cung cấp dịch vụ của ch&uacute;ng t&ocirc;i.&nbsp;Để biết th&ecirc;m th&ocirc;ng tin về c&aacute;ch ch&uacute;ng t&ocirc;i sử dụng c&aacute;c c&ocirc;ng nghệ n&agrave;y&nbsp;(bao gồm danh s&aacute;ch c&aacute;c c&ocirc;ng ty kh&aacute;c đặt Cookie tr&ecirc;n trang Web của ch&uacute;ng t&ocirc;i,&nbsp;danh s&aacute;ch c&aacute;c Cookie m&agrave; ch&uacute;ng t&ocirc;i đặt khi cung cấp c&aacute;c dịch vụ,&nbsp;giải th&iacute;ch về c&aacute;ch bạn c&oacute; thể chọn kh&ocirc;ng tham gia một số loại Cookie),&nbsp;vui l&ograve;ng tham khảo <strong>Ch&iacute;nh s&aacute;ch Cookie</strong> của ch&uacute;ng t&ocirc;i.</p>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'>&nbsp;</p>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'><span style='font-family:"Times New Roman",serif;color:#1F3763;font-weight:bold;'>C&aacute;ch thức li&ecirc;n hệ với ch&uacute;ng t&ocirc;i</span> :</p>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;text-align:justify;'>Nếu bạn muốn hỏi về th&ocirc;ng tin,&nbsp;đưa ra y&ecirc;u cầu li&ecirc;n quan hoặc khiếu nại về c&aacute;ch ch&uacute;ng t&ocirc;i xử l&yacute; th&ocirc;ng tin c&aacute; nh&acirc;n của bạn,&nbsp;vui l&ograve;ng li&ecirc;n hệ với Bộ phận hỗ trợ của e-Gate hoặc gửi thư cho ch&uacute;ng t&ocirc;i theo một trong c&aacute;c địa chỉ b&ecirc;n dưới. Nếu bạn muốn gửi một y&ecirc;u cầu r&agrave;ng buộc ph&aacute;p l&yacute; để thu thập th&ocirc;ng tin c&aacute; nh&acirc;n của người kh&aacute;c ( v&iacute; dụ: nếu bạn c&oacute; tr&aacute;t đ&ograve;i hầu t&ograve;a hay lệnh của t&ograve;a &aacute;n),&nbsp;vui l&ograve;ng xem lại <strong>Nguy&ecirc;n tắc của ch&uacute;ng t&ocirc;i về Y&ecirc;u cầu ph&aacute;p l&yacute;</strong><strong>.</strong></p>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;text-align:center;'><strong><span style="font-size:21px;line-height:107%;color:#203864;">Ch&iacute;nh s&aacute;ch cho ứng dụng Camera</span></strong><span style="font-size:21px;line-height:107%;color:#203864;">&nbsp;:</span></p>
          <p style='margin-right:0cm;margin-left:0cm;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'>&nbsp;</p>
          <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>
              <ul style="margin-bottom:0cm;list-style-type: disc;">
                  <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>Th&ocirc;ng tin ch&uacute;ng t&ocirc;i nhận được khi bạn sử dụng dịch vụ của ch&uacute;ng t&ocirc;i :</li>
              </ul>
          </div>
          <p style='margin-right:0cm;margin-left:18.0pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'>&nbsp; &nbsp; Khi bạn sử dụng dịch vụ của ch&uacute;ng t&ocirc;i,hệ thống sẽ thu thập th&ocirc;ng tin về h&igrave;nh ảnh của bạn th&ocirc;ng qua chức năng camera cũng như thu thập h&igrave;nh ảnh v&agrave; th&ocirc;ng tin kh&aacute;c từ m&aacute;y ảnh v&agrave; ảnh tr&ecirc;n thiết bị của bạn</p>
          <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>
              <ul style="margin-bottom:0cm;list-style-type: disc;">
                  <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>C&aacute;ch ch&uacute;ng t&ocirc;i sử dụng th&ocirc;ng tin :</li>
              </ul>
          </div>
          <p style='margin-right:0cm;margin-left:18.0pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'>&nbsp; &nbsp;Tăng cường sự bảo mất v&agrave; an to&agrave;n cho c&aacute;c sản phẩm dịch vụ của ch&uacute;ng t&ocirc;i ( sử dụng th&ocirc;ng tin của bạn để x&aacute;c định quyền truy cập,sử dụng dịch vụ ..)</p>
          <p style='margin-right:0cm;margin-left:18.0pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'>X&aacute;c minh danh t&iacute;nh của bạn v&agrave; ngăn chặn việc gian lận hoặc c&aacute;c hoạt động bất hợp ph&aacute;p hoặc bất hợp t&aacute;c kh&aacute;c</p>
          <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>
              <ul style="margin-bottom:0cm;list-style-type: disc;">
                  <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>C&aacute;ch ch&uacute;ng t&ocirc;i chia sẻ th&ocirc;ng tin:</li>
              </ul>
          </div>
          <p style='margin-right:0cm;margin-left:18.0pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'>Th&ocirc;ng tin n&agrave;y sẽ được ch&uacute;ng t&ocirc;i lưu trữ tạm thời trong nội bộ,kh&ocirc;ng chia sẻ dưới bất k&igrave; h&igrave;nh thức n&agrave;o cho bất k&igrave; tổ chức n&agrave;o.</p>
          <div style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>
              <ul style="margin-bottom:0cm;list-style-type: disc;">
                  <li style='margin-top:0cm;margin-right:0cm;margin-bottom:8.0pt;margin-left:0cm;line-height:107%;font-size:17px;font-family:"Times New Roman",serif;'>Ch&uacute;ng t&ocirc;i sẽ giữ th&ocirc;ng tin của bạn trong bao l&acirc;u :</li>
              </ul>
          </div>
          <p style='margin-right:0cm;margin-left:18.0pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'>Th&ocirc;ng tin được lưu trữ tạm thời cho đ&ecirc;n khi qu&aacute; tr&igrave;nh định danh của bạn ho&agrave;n th&agrave;nh v&agrave; sẽ x&oacute;a ngay sau đ&oacute;</p>
          <p style='margin-right:0cm;margin-left:18.0pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'>&nbsp;</p>
          <p style='margin-right:0cm;margin-left:18.0pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;text-align:center;'><strong><span style="font-size:21px;line-height:107%;color:#203864;">Ch&iacute;nh s&aacute;ch h&igrave;nh ảnh</span></strong></p>
          <p style='margin-right:0cm;margin-left:18.0pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'>Ảnh l&agrave; một trong những phần quan trọng nhất trong danh s&aacute;ch của bạn v&igrave; ch&uacute;ng cho ph&eacute;p người mua tiềm năng nh&igrave;n thấy t&igrave;nh trạng ch&iacute;nh x&aacute;c của mặt h&agrave;ng v&agrave; gi&uacute;p họ quyết định mua h&agrave;ng. Ch&uacute;ng t&ocirc;i khuy&ecirc;n bạn n&ecirc;n bao gồm nhiều hơn một để gi&uacute;p tăng cơ hội b&aacute;n h&agrave;ng, giao h&agrave;ng th&agrave;nh c&ocirc;ng.</p>
          <p style='margin-right:0cm;margin-left:18.0pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'><em>&nbsp;</em></p>
          <p style='margin-right:0cm;margin-left:18.0pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'>Những điều sau đ&acirc;y kh&ocirc;ng được ph&eacute;p:</p>
          <p style='margin-right:0cm;margin-left:18.0pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'>&nbsp;</p>
          <ol style="list-style-type: decimal;margin-left:44px;">
              <li>Ảnh kh&ocirc;ng thể hiện ch&iacute;nh x&aacute;c mặt h&agrave;ng</li>
              <li>H&igrave;nh ảnh tr&igrave;nh giữ chỗ được sử dụng để truyền tải th&ocirc;ng điệp</li>
              <li>Kho ảnh cho c&aacute;c mặt h&agrave;ng đ&atilde; qua sử dụng, bị hư hỏng hoặc bị lỗi</li>
              <li>Ảnh c&oacute; th&ecirc;m đường viền</li>
              <li>Ảnh c&oacute; th&ecirc;m văn bản, t&aacute;c phẩm nghệ thuật hoặc t&agrave;i liệu tiếp thị</li>
              <li>H&igrave;nh mờ thuộc bất kỳ loại n&agrave;o, bao gồm cả những h&igrave;nh mờ được sử dụng để ph&acirc;n bổ quyền sở hữu</li>
          </ol>
          <p style='margin-right:0cm;margin-left:18.0pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'>&nbsp;</p>
          <p style='margin-right:0cm;margin-left:18.0pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'>Hoạt động kh&ocirc;ng tu&acirc;n theo ch&iacute;nh s&aacute;ch của e-Gate c&oacute; thể dẫn đến một loạt c&aacute;c h&agrave;nh động, chẳng hạn như: kết th&uacute;c hoặc hủy danh s&aacute;ch về mặt h&agrave;nh ch&iacute;nh, ẩn hoặc hạ cấp tất cả danh s&aacute;ch khỏi kết quả t&igrave;m kiếm, kho&aacute; t&agrave;i khoản, hạn chế sử dụng App v&agrave; tạm ngưng t&agrave;i khoản. Tất cả c&aacute;c khoản ph&iacute; đ&atilde; trả hoặc phải trả li&ecirc;n quan đến danh s&aacute;ch hoặc t&agrave;i khoản m&agrave; ch&uacute;ng t&ocirc;i thực hiện bất kỳ h&agrave;nh động n&agrave;o sẽ kh&ocirc;ng được ho&agrave;n trả hoặc ghi c&oacute; v&agrave;o t&agrave;i khoản của bạn.</p>
          <p style='margin-right:0cm;margin-left:18.0pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'><strong>&nbsp;</strong></p>
          <p style='margin-right:0cm;margin-left:18.0pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'><strong><span style="color:#203864;">Mẹo</span></strong></p>
          <p style='margin-right:0cm;margin-left:18.0pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'>Truy cập Trợ gi&uacute;p người b&aacute;n để t&igrave;m chi tiết về bất kỳ vấn đề ch&iacute;nh s&aacute;ch n&agrave;o với t&agrave;i khoản hoặc danh s&aacute;ch của bạn v&agrave; nhận th&ocirc;ng tin bạn cần để nhanh ch&oacute;ng giải quyết ch&uacute;ng.</p>
          <p style='margin-right:0cm;margin-left:18.0pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'>&nbsp;</p>
          <p style='margin-right:0cm;margin-left:18.0pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'><strong><span style="color:#203864;">Tại sao e-Gate c&oacute; ch&iacute;nh s&aacute;ch n&agrave;y?</span></strong></p>
          <p style='margin-right:0cm;margin-left:18.0pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'>H&igrave;nh ảnh chất lượng cải thiện trải nghiệm mua h&agrave;ng, trải nghiệm ứng dụng, do đ&oacute;, danh s&aacute;ch tu&acirc;n theo c&aacute;c quy tắc n&agrave;y c&oacute; nhiều khả năng tiềm năng hơn. C&aacute;c quy tắc n&agrave;y cũng đảm bảo rằng ảnh của bạn tu&acirc;n theo c&aacute;c quy tắc của c&aacute;c c&ocirc;ng cụ t&igrave;m kiếm phổ biến tr&ecirc;n internet.</p>
          <p style='margin-right:0cm;margin-left:18.0pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'>&nbsp;</p>
          <h1 style='margin-top:12.0pt;margin-right:0cm;margin-bottom:.0001pt;margin-left:0cm;text-align:center;line-height:107%;font-size:21px;font-family:"Times New Roman",serif;color:#203864;font-weight:bold;'>Ch&iacute;nh s&aacute;ch Cookie</h1>
          <h4 style='margin-top:0cm;margin-right:0cm;margin-bottom:15.0pt;margin-left:21.3pt;line-height:107%;font-size:17px;font-family:"Calibri Light",sans-serif;color:#2F5496;font-weight:normal;font-style:italic;background:white;'><span style='line-height:107%;font-family:"Times New Roman",serif;color:windowtext;'>Ch&uacute; &yacute; quan trọng: vui l&ograve;ng đọc kỹ trước khi sử dụng ứng dụng e-Gate.</span></h4>
          <p style='margin-right:0cm;margin-left:21.3pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;background:white;'><span style="font-size:17px;">Ch&iacute;nh s&aacute;ch n&agrave;y được soạn thảo nhằm giải th&iacute;ch c&aacute;ch sử dụng cookie tr&ecirc;n ứng dụng. Ch&iacute;nh s&aacute;ch c&oacute; thể được sửa đổi theo thời gian. Khi sửa đổi, ch&uacute;ng t&ocirc;i sẽ b&aacute;o cho bạn biết bằng c&aacute;c phương tiện th&iacute;ch hợp như đăng ch&iacute;nh s&aacute;ch sửa đổi tr&ecirc;n trang n&agrave;y với ng&agrave;y&quot;cập nhật mới nhất&quot;. Bằng c&aacute;ch sử dụng ứng dụng của ch&uacute;ng t&ocirc;i, bạn đ&atilde; đồng &yacute; với việc đặt cookie tr&ecirc;n m&aacute;y t&iacute;nh của bạn theo c&aacute;c điều khoản của ch&iacute;nh s&aacute;ch n&agrave;y. Nếu bạn kh&ocirc;ng muốn chấp nhận cookie từ trang web n&agrave;y, vui l&ograve;ng tắt cookie hoặc kh&ocirc;ng sử dụng ứng dụng của ch&uacute;ng t&ocirc;i.</span></p>
          <h4 style='margin-top:0cm;margin-right:0cm;margin-bottom:15.0pt;margin-left:21.3pt;line-height:107%;font-size:17px;font-family:"Calibri Light",sans-serif;color:#2F5496;font-weight:normal;font-style:italic;background:white;'><strong><span style='line-height:107%;font-family:"Times New Roman",serif;color:#203864;font-style:normal;'><span style="color:windowtext;">Cookie l&agrave; g&igrave;?</span></span></strong></h4>
          <p style='margin-right:0cm;margin-left:21.3pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;background:white;'><span style="font-size:17px;">Cookie l&agrave; một chuỗi th&ocirc;ng tin chỉ c&oacute; văn bản m&agrave; một trang web chuyển sang tệp cookie của tr&igrave;nh duyệt tr&ecirc;n đĩa cứng m&aacute;y t&iacute;nh của bạn; V&igrave; thế, &nbsp;ứng dụng sẽ nhận ra khi bạn truy cập lại v&agrave; nhớ th&ocirc;ng tin nhất định cũng như sở th&iacute;ch của bạn. Cookie được thiết kế để chứa một lượng dữ liệu nhỏ d&agrave;nh ri&ecirc;ng cho một kh&aacute;ch h&agrave;ng v&agrave; &nbsp;ứng dụng cụ thể, v&agrave; c&oacute; thể truy cập bởi m&aacute;y chủ web hoặc m&aacute;y t&iacute;nh của người truy cập. Ch&uacute;ng c&oacute; thể bao gồm những trang n&agrave;o đ&atilde; được truy cập, c&aacute;c t&ugrave;y chọn bạn đ&atilde; thực hiện, bất kỳ th&ocirc;ng tin cụ thể n&agrave;o bạn đ&atilde; nhập v&agrave;o biểu mẫu v&agrave; thời gian v&agrave; ng&agrave;y của lần truy cập trước đ&oacute; của bạn. Cookie được sử dụng rộng r&atilde;i để cải thiện trải nghiệm người d&ugrave;ng hơn.</span></p>
          <p style='margin-right:0cm;margin-left:21.3pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;background:white;'><span style="font-size:17px;">Ch&iacute;nh s&aacute;ch cookie l&agrave; một y&ecirc;u cầu ph&aacute;p l&yacute; đối với c&aacute;c &nbsp;ứng dụng ở ch&acirc;u &Acirc;u với Luật Cookie mới của EU, được tất cả c&aacute;c nước th&agrave;nh vi&ecirc;n EU &aacute;p dụng v&agrave;o th&aacute;ng 5 năm 2011. Cookie được thiết kế để bảo vệ quyền ri&ecirc;ng tư trực tuyến, bằng c&aacute;ch khiến người ti&ecirc;u d&ugrave;ng biết về c&aacute;ch thu thập v&agrave; sử dụng th&ocirc;ng tin về ch&uacute;ng trực tuyến, v&agrave; cho họ lựa chọn cho ph&eacute;p hay kh&ocirc;ng.</span></p>
          <h4 style='margin-top:0cm;margin-right:0cm;margin-bottom:15.0pt;margin-left:21.3pt;line-height:107%;font-size:17px;font-family:"Calibri Light",sans-serif;color:#2F5496;font-weight:normal;font-style:italic;background:white;'><strong><span style='line-height:107%;font-family:"Times New Roman",serif;color:#203864;font-style:normal;'><span style="color:windowtext;">C&aacute;c loại Cookie</span></span></strong></h4>
          <p style='margin-right:0cm;margin-left:21.3pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;background:white;'><span style="font-size:17px;">C&oacute; hai loại cookie ch&iacute;nh:</span></p>
          <ul style="list-style-type: disc;margin-left:11.3px;">
              <li><span style='font-family:"Times New Roman";font-size:17px;'>Cookie phi&ecirc;n (Session cookies): đ&acirc;y l&agrave; c&aacute;c cookie chỉ tồn tại tạm thời khi người d&ugrave;ng duyệt web. Ch&uacute;ng cho ph&eacute;p &nbsp;ứng dụng nhận ra bạn khi bạn đang điều hướng giữa c&aacute;c trang trong một phi&ecirc;n tr&igrave;nh duyệt duy nhất v&agrave; cho ph&eacute;p bạn sử dụng ứng dụng một c&aacute;ch hiệu quả nhất.</span></li>
              <li><span style='font-family:"Times New Roman";font-size:17px;'>Cookie cố định (Persistent cookies): ch&uacute;ng được lưu trữ tr&ecirc;n thiết bị của bạn giữa c&aacute;c phi&ecirc;n duyệt cho đến khi hết hạn hoặc x&oacute;a c&aacute;c cookie n&agrave;y. Do đ&oacute;, ch&uacute;ng cho ph&eacute;p trang web nhận ra bạn khi bạn trở về, ghi nhớ sở th&iacute;ch của bạn v&agrave; dịch vụ ph&ugrave; hợp với bạn.</span></li>
          </ul>
          <p style='margin-right:0cm;margin-left:21.3pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;background:white;'><span style="font-size:17px;">Ngo&agrave;i c&aacute;c cookie phi&ecirc;n v&agrave; cố định, c&oacute; thể c&oacute; c&aacute;c cookie kh&aacute;c được đặt bởi &nbsp;ứng dụng m&agrave; bạn đ&atilde; chọn truy cập, chẳng hạn như &nbsp;ứng dụng của ch&uacute;ng t&ocirc;i, để cung cấp th&ocirc;ng tin cho ch&uacute;ng t&ocirc;i hoặc c&aacute;c b&ecirc;n thứ ba.</span></p>
          <h4 style='margin-top:0cm;margin-right:0cm;margin-bottom:15.0pt;margin-left:21.3pt;line-height:107%;font-size:17px;font-family:"Calibri Light",sans-serif;color:#2F5496;font-weight:normal;font-style:italic;background:white;'><strong><span style='line-height:107%;font-family:"Times New Roman",serif;color:windowtext;font-style:normal;'>Sử dụng cookie tr&ecirc;n ứng dụng của ch&uacute;ng t&ocirc;i</span></strong></h4>
          <h4 style='margin-top:0cm;margin-right:0cm;margin-bottom:.0001pt;margin-left:21.3pt;line-height:107%;font-size:17px;font-family:"Calibri Light",sans-serif;color:#2F5496;font-weight:normal;font-style:italic;background:white;'><strong><span style='line-height:107%;font-family:"Times New Roman",serif;color:#203864;font-style:normal;'><span style="color:windowtext;">C&aacute;ch từ chối hoặc x&oacute;a cookie tr&ecirc;n ứng dụng của ch&uacute;ng t&ocirc;i</span></span></strong></h4>
          <p style='margin-right:0cm;margin-left:21.3pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;background:white;'><span style="font-size:17px;">Hầu hết c&aacute;c tr&igrave;nh duyệt, ứng dụng được thiết lập để chấp nhận cookie. Tuy nhi&ecirc;n, bạn c&oacute; khả năng tắt cookie nếu muốn, thường l&agrave; th&ocirc;ng qua thay đổi c&agrave;i đặt của bạn. Cũng c&oacute; thể định cấu h&igrave;nh c&agrave;i đặt tr&igrave;nh duyệt, ứng dụng của bạn để cho ph&eacute;p chấp nhận cookie cụ thể hoặc th&ocirc;ng b&aacute;o cho bạn mỗi khi cookie mới sắp được lưu trữ tr&ecirc;n m&aacute;y t&iacute;nh của bạn, điều n&agrave;y cho ph&eacute;p bạn quyết định chấp nhận hoặc từ chối cookie.</span></p>
          <p style='margin-right:0cm;margin-left:21.3pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'><span style="line-height:107%;">Để quản l&yacute; việc sử dụng cookie, c&oacute; nhiều t&agrave;i nguy&ecirc;n kh&aacute;c nhau c&oacute; sẵn cho bạn, v&iacute; dụ như phần &quot;Trợ gi&uacute;p&quot; tr&ecirc;n tr&igrave;nh duyệt của bạn. Bạn cũng c&oacute; thể v&ocirc; hiệu h&oacute;a hoặc x&oacute;a dữ liệu được lưu trữ được sử dụng bởi c&ocirc;ng nghệ tương tự như cookie, chẳng hạn như Đối tượng chia sẻ cục bộ hoặc cookie Flash, bằng c&aacute;ch quản l&yacute; &quot;c&agrave;i đặt add-on&quot; của tr&igrave;nh duyệt, hoặc hoặc truy cập &nbsp;ứng dụng của nh&agrave; sản xuất.</span></p>
          <p style='margin-right:0cm;margin-left:21.3pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'><strong>INGROUP&nbsp;</strong></p>
          <p style='margin-right:0cm;margin-left:21.3pt;font-size:17px;font-family:"Times New Roman",serif;margin-top:0cm;margin-bottom:8.0pt;line-height:107%;'><strong>( ADDRESS,SĐT,EMAIL)</strong></p>
          
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
<script>
export default {
    beforeCreate() {
            document.querySelector(".footer-top").style.display = "none";
    }
}
</script>