<script src="{{url('themes/assets/js/jquery.min.js')}}"></script>
<script src="{{url('themes/assets/js/jquery.validate.min.js')}}"></script>
<script src="{{url('themes/assets/libs/bootstrap/js/bootstrap.min.js')}}"></script>
<script src="{{url('themes/assets/libs/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<script src="{{url('themes/assets/libs//toastr/toastr.min.js')}}"></script>
<script src="{{url('themes/assets/js/show-password.js')}}"></script>
<script src="{{url('themes/assets/js/authentication-main.js')}}"></script>

{{-- <script src="{{url('themes/assets/js/select2.js')}}"></script> --}}
{{-- <script src="{{url('themes/assets/js/select2.min.js')}}"></script> --}}
<script src="{{url('themes/assets/libs/moment\min\moment.min.js')}}"></script>
<script src="{{asset('themes/assets/libs/ckeditor/ckeditor.js')}}"></script>
<script src="{{asset('themes/assets/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('themes/assets/js/dataTables.bootstrap5.min.js')}}"></script>
<script src="{{url('themes/assets/js/sticky.js')}}"></script>
<script src="{{url('themes/assets/libs/choices.js/public/assets/scripts/choices.min.js')}}"></script>
<script src="{{url('themes/assets/libs/@popperjs/core/umd/popper.min.js')}}"></script>
<script src="{{url('themes/assets/js/defaultmenu.min.js')}}"></script>
{{-- <script src="{{url('themes/assets/js/custom-switcher.min.js')}}"></script> --}}
<script src="{{url('themes/assets/libs/node-waves/waves.min.js')}}"></script>
<script src="{{url('themes/assets/libs/simplebar/simplebar.min.js')}}"></script>
<script src="{{url('themes/assets/js/simplebar.js')}}"></script>
<script src="{{url('themes/assets/libs/@simonwep/pickr/pickr.es5.min.js')}}"></script>
<script src="{{url('themes/assets/js/main.js')}}"></script>
{{-- <script src="{{url('themes/assets/js/index.js')}}"></script> --}}
{{-- <script src="{{url('themes/assets/js/custom.js')}}"></script> --}}
