<script src="{{asset('theme/assets/bootstrap/bootstrap.min.js')}}"></script>
<script src="{{asset('theme/assets/plugins/jquery/jquery.min.js')}}"></script>
<script src="{{asset('theme/assets/plugins/jquery-validation/jquery.validate.min.js')}}"></script>
<script src="{{ asset('theme/assets/plugins/jquery-validation/additional-methods.min.js')}}"></script>
<script src="{{asset('theme/assets/plugins/jquery/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('theme/assets/bootstrap/dataTables.bootstrap5.min.js')}}"></script>
<script src="{{asset('theme/assets/plugins/toastr/toastr.min.js')}}"></script>
<script src="{{asset('theme/assets/plugins/ckeditor/ckeditor.js')}}"></script>
<script src="{{asset('theme/assets/plugins/countdown/moment.min.js')}}"></script>
